(function(){
function addTrust(){var nav=document.querySelector('.nav');if(nav&&!nav.querySelector('.jubilee-link')){var a=document.createElement('a');a.className='item jubilee-link';a.href='https://www.magyariskola.at/tortenetunk';a.target='_blank';a.rel='noopener';a.textContent='1987–2027 · 40 éves BMI';var report=nav.querySelector('.btn.sun');nav.insertBefore(a,report||null)}var drawer=document.querySelector('#drawer .wrap');if(drawer&&!drawer.querySelector('.jubilee-mobile')){var m=document.createElement('a');m.className='jubilee-mobile';m.href='https://www.magyariskola.at/tortenetunk';m.target='_blank';m.rel='noopener';m.textContent='1987–2027 · 40 éves BMI';var firstExternal=drawer.querySelector('a[href="https://2026.magyariskola.at"]');drawer.insertBefore(m,firstExternal||null)}var stat=[].slice.call(document.querySelectorAll('.stat')).find(function(el){return /helyszín/.test(el.textContent)});if(stat){var b=stat.querySelector('b');if(b&&b.textContent.trim()==='4')b.textContent='5+'}var footer=document.querySelector('.site-foot .wrap');if(footer&&!footer.querySelector('.footer-trust')){var div=document.createElement('div');div.className='footer-trust';div.setAttribute('aria-label','Hitelesség és sajtó');div.innerHTML='<p class="official-note"><strong>A Bécsi Magyar Iskola (BMI) hivatalos programválasztója.</strong> A Wiener Ungarische Schule 1987 szeptemberében indult; 2027-ben ünnepli fennállásának 40. évfordulóját. Fenntartója az Ausztriai Magyar Egyesületek és Szervezetek Központi Szövetsége.</p><div class="trust-links"><a href="https://www.magyariskola.at/tortenetunk" target="_blank" rel="noopener">Történetünk · 1987–2027</a><a href="https://hu.wikipedia.org/wiki/B%C3%A9csi_Magyar_Iskola" target="_blank" rel="noopener">Wikipédia</a><a href="https://rolunk.at/nepcsoportunk/a-megujult-becsi-magyar-iskola-elmult-egy-eve-video/" target="_blank" rel="noopener">Rólunk.at · A megújult BMI</a><a href="https://rolunk.at/kultura/ujdonsagok-a-becsi-magyar-iskola-2024-25-os-taneveben/" target="_blank" rel="noopener">Rólunk.at · Oktatás és programok</a></div><p class="creator-credit">Készítette a <strong>VIPACH Be Smart Kids Club csapata</strong> · <a href="https://rolunk.at/aktualis/a-fiataloknak-ma-mar-bizonyitek-kell-egy-becsi-kreativ-kozosseg-uj-generaciot-epit/" target="_blank" rel="noopener">Ismerd meg a projektet a Rólunk.at cikkében</a></p>';footer.appendChild(div)}}
addTrust();
var root=document.getElementById('wizard');if(!root)return;
var cfg=window.BMI_FINDER;if(!cfg||!Array.isArray(cfg.programs)){root.innerHTML='<div class="wizard-card"><h3>A kereső átmenetileg nem elérhető</h3><p>Az összes foglalkozást továbbra is meg tudod nézni.</p><a class="btn" href="foglalkozasok.html">Összes foglalkozás</a></div>';return}
var steps=[
 {key:'age',title:'Kinek keresel programot?',text:'Válaszd ki a korosztályt. Ez az első és legfontosabb szűrő.',options:cfg.ages},
 {key:'interest',title:'Mi érdekli leginkább?',text:'Válaszd azt, amihez most a leginkább kedve lenne.',options:cfg.interests},
 {key:'day',title:'Mikor lenne a legjobb?',text:'Ha mindegy, a rendszer minden megfelelő napot figyelembe vesz.',options:cfg.days},
 {key:'pace',title:'Milyen ritmus fér bele?',text:'Rendszeres programot vagy inkább ritkább, rugalmasabb alkalmakat kerestek?',options:cfg.pace}
];
var state={},idx=0;
function esc(s){return String(s).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function progress(n){document.querySelectorAll('#prog i').forEach(function(b,i){b.classList.toggle('on',i<=n)})}
function render(){progress(idx);var s=steps[idx],html='<div class="wizard-card"><div class="kicker">'+(idx+1)+' / '+steps.length+'</div><h3>'+esc(s.title)+'</h3><p>'+esc(s.text)+'</p><div class="choice-grid">';s.options.forEach(function(o){html+='<button class="choice" type="button" data-value="'+esc(o.id)+'">'+esc(o.label)+'</button>'});html+='</div>';if(idx>0)html+='<div class="wizard-nav"><button class="btn ghost" type="button" data-back>Vissza</button></div>';html+='</div>';root.innerHTML=html;root.querySelectorAll('[data-value]').forEach(function(btn){btn.addEventListener('click',function(){state[s.key]=this.dataset.value;if(idx<steps.length-1){idx++;render()}else showResults()})});var back=root.querySelector('[data-back]');if(back)back.addEventListener('click',function(){idx--;render()})}
function score(p){var n=0;if(p.interests.indexOf(state.interest)!==-1)n+=6;if(state.day==='mindegy')n+=1;else if(p.day===state.day)n+=3;else n-=2;if(state.pace==='mindegy')n+=1;else if(p.pace===state.pace)n+=2;return n}
function matchText(p){var parts=[];if(p.interests.indexOf(state.interest)!==-1)parts.push('az érdeklődési körötökhöz illik');if(state.day==='mindegy'||p.day===state.day)parts.push('az időpont-preferenciátokkal összeegyeztethető');if(state.pace==='mindegy'||p.pace===state.pace)parts.push('a választott rendszerességhez passzol');return parts.length?parts.join(', ')+'.':'A korosztály alapján megfelelő, de az időpont vagy a ritmus kompromisszumot kérhet.'}
function showResults(){progress(4);var eligible=cfg.programs.filter(function(p){return p.ages.indexOf(state.age)!==-1}).map(function(p,i){return{p:p,score:score(p),order:i}}).sort(function(a,b){return b.score-a.score||a.order-b.order});var top=eligible.slice(0,Math.min(3,eligible.length));var age=(cfg.ages.find(function(a){return a.id===state.age})||{}).label||'';var html='<div class="wizard-card"><span class="kicker">Személyre szabott ajánlás</span><h3 style="margin-top:8px">Ezek illenek leginkább</h3><p><strong>'+esc(age)+'</strong> korosztályból indultunk, majd figyelembe vettük az érdeklődést, a választott napot és a rendszerességet. A regisztráció minden ajánlásnál közvetlenül elérhető.</p><div class="result-grid">';
 top.forEach(function(r){var p=r.p;html+='<article class="result-card"><b>'+esc(p.name)+'</b><span class="result-when">'+esc(p.when)+'</span><p>'+esc(p.why)+'</p><p class="result-reason"><strong>Miért ezt?</strong> '+esc(matchText(p))+'</p><p><a class="btn" href="'+esc(p.url)+'" target="_blank" rel="noopener">Regisztráció / jelentkezés</a></p></article>'});
 html+='</div>';
 if(!top.length)html+='<p>Ehhez a korosztályhoz most nem található megfelelő program. <a href="foglalkozasok.html">Nézd meg a teljes kínálatot.</a></p>';
 html+='<div class="wizard-nav"><button class="btn ghost" type="button" data-restart>Újrakezdem</button><a class="btn ghost" href="foglalkozasok.html">Mind a 22 program</a></div></div>';
 root.innerHTML=html;var restart=root.querySelector('[data-restart]');if(restart)restart.addEventListener('click',function(){state={};idx=0;render()})}
render();
})();