(function(){
'use strict';
var cfg=window.BMI_FINDER;
if(!cfg||!Array.isArray(cfg.programs))return;
var programs=cfg.programs;
var lang=(document.documentElement.lang||'hu').toLowerCase();
var locale=lang.indexOf('de')===0?'de':(lang.indexOf('en')===0?'en':'hu');
var I18N={
 hu:{days:{hetfo:'Hétfő',kedd:'Kedd',szerda:'Szerda',csutortok:'Csütörtök',pentek:'Péntek',szombat:'Szombat',vasarnap:'Vasárnap',rugalmas:'Rugalmas'},regular:'Rendszeres',flex:'Ritkább / rugalmasabb',own:'BMI saját program',partner:'Partnerprogram',bmiPartner:'BMI Partner Program',age:'Korosztály',language:'Nyelv',when:'Mikor',location:'Helyszín',situation:'Milyen helyzetre?',outcome:'Mit ad?',period:'Időszak / alkalmak',teacher:'Oktató',background:'Oktatói háttér',contact:'Oktatói elérhetőség',fee:'Hozzájárulási díj',payment:'Befizetési határidő',enrollment:'Csatlakozás',first:'Első alkalom',deadline:'Jelentkezési határidő',capacity:'Létszámkorlát',trial:'Próbaalkalom',relation:'Programkapcsolat',provider:'Foglalkozásgazda',cta:'Részletek és jelentkezés',unit:'foglalkozás'},
 de:{days:{hetfo:'Montag',kedd:'Dienstag',szerda:'Mittwoch',csutortok:'Donnerstag',pentek:'Freitag',szombat:'Samstag',vasarnap:'Sonntag',rugalmas:'Flexibel'},regular:'Regelmäßig',flex:'Seltener / flexibel',own:'Programm der Wiener Ungarischen Schule',partner:'Partnerprogramm',bmiPartner:'BMI-Partnerprogramm',age:'Alter',language:'Sprache',when:'Termin',location:'Ort',situation:'Für wen geeignet?',outcome:'Was bietet das Programm?',period:'Zeitraum / Termine',teacher:'Leitung',background:'Fachlicher Hintergrund',contact:'Kontakt',fee:'Teilnahmebeitrag',payment:'Zahlungsfrist',enrollment:'Teilnahme',first:'Erster Termin',deadline:'Anmeldefrist',capacity:'Teilnehmerzahl',trial:'Schnuppertermin',relation:'Programmtyp',provider:'Veranstalter',cta:'Details und Anmeldung',unit:'Programme'},
 en:{days:{hetfo:'Monday',kedd:'Tuesday',szerda:'Wednesday',csutortok:'Thursday',pentek:'Friday',szombat:'Saturday',vasarnap:'Sunday',rugalmas:'Flexible'},regular:'Regular',flex:'Occasional / flexible',own:'Vienna Hungarian School program',partner:'Partner program',bmiPartner:'BMI Partner Program',age:'Age group',language:'Language',when:'Schedule',location:'Location',situation:'Who is it for?',outcome:'What does it offer?',period:'Period / sessions',teacher:'Teacher / leader',background:'Professional background',contact:'Contact',fee:'Fee',payment:'Payment deadline',enrollment:'Joining',first:'First session',deadline:'Registration deadline',capacity:'Capacity',trial:'Trial session',relation:'Program type',provider:'Provider',cta:'Details and registration',unit:'programs'}
};
var tx=I18N[locale];
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]})}
function ageLabel(p){if(locale!=='hu')return p.maxAge===99?p.minAge+'+':p.minAge+'–'+p.maxAge;return p.ageText||((p.minAge===18&&p.maxAge===99)?'18+':(p.maxAge===99?p.minAge+'+':p.minAge+'–'+p.maxAge+' év'))}
function weekdayLabel(v){return tx.days[v]||v}
function weekdayLabels(p){return(p.weekdays||[p.weekday]).map(weekdayLabel).join(' + ')}
function schemaDay(v){return{hetfo:'https://schema.org/Monday',kedd:'https://schema.org/Tuesday',szerda:'https://schema.org/Wednesday',csutortok:'https://schema.org/Thursday',pentek:'https://schema.org/Friday',szombat:'https://schema.org/Saturday',vasarnap:'https://schema.org/Sunday'}[v]||null}
function paceLabel(p){return p.pace==='rugalmas'?tx.flex:tx.regular}
function providerLabel(p){if(p.relationship==='bmi-partner')return'BMI Partner Program';return p.provider==='BMI'?'Bécsi Magyar Iskola':p.provider}
function relationLabel(p){if(p.relationship==='bmi')return tx.own;if(p.relationship==='bmi-partner')return tx.bmiPartner;return tx.partner}
function providerSchema(p){if(p.relationship==='bmi')return{'@id':'https://www.magyariskola.at/#org'};if(p.relationship==='bmi-partner')return null;var url=p.url;if(p.provider==='Napraforgók')url='https://napraforgok.at/';if((p.provider||'').indexOf('Cserkészcsapat')>-1)url='https://cserkesz.at/cserkesz-raj/';return{'@type':'Organization','name':p.provider,'url':url}}
function detail(label,value){return value?'<li><span class="k">'+esc(label)+'</span><span>'+esc(value)+'</span></li>':''}
function card(p){var weekdays=(p.weekdays||[p.weekday]).join(' ');return'<article class="item program-card" id="'+esc(p.id)+'" data-day="'+esc(p.day)+'" data-weekday="'+esc(p.weekday)+'" data-weekdays="'+esc(weekdays)+'" data-pace="'+esc(p.pace)+'" data-min-age="'+p.minAge+'" data-max-age="'+p.maxAge+'"><h3><a href="'+esc(p.url)+'" target="_blank" rel="noopener">'+esc(p.name)+'</a></h3><div class="sub">'+esc(p.why)+'</div><div class="chips"><span class="chip age">'+esc(ageLabel(p))+'</span><span class="chip">'+esc(weekdayLabels(p))+'</span><span class="chip">'+esc(paceLabel(p))+'</span><span class="chip">'+esc(relationLabel(p))+'</span></div><ul class="kv">'+detail(tx.age,ageLabel(p))+detail(tx.language,p.language)+detail(tx.when,p.when)+detail(tx.location,p.location)+detail(tx.situation,p.painPoint)+detail(tx.outcome,p.outcome)+detail(tx.period,p.period)+detail(tx.teacher,p.teacher)+detail(tx.background,p.teacherBackground)+detail(tx.contact,p.teacherContact)+detail(tx.fee,p.fee)+detail(tx.payment,p.paymentDeadline)+detail(tx.enrollment,p.enrollment)+detail(tx.first,p.firstDate)+detail(tx.deadline,p.registrationDeadline)+detail(tx.capacity,p.capacity)+detail(tx.trial,p.trial)+detail(tx.relation,relationLabel(p))+detail(tx.provider,providerLabel(p))+'</ul><p class="card-action"><a class="btn" href="'+esc(p.url)+'" target="_blank" rel="noopener">'+esc(tx.cta)+'</a></p></article>'}
function courseSchema(p){var schedule={'@type':'Schedule','repeatFrequency':paceLabel(p)};var days=(p.weekdays||[p.weekday]).map(schemaDay).filter(Boolean);if(days.length)schedule.byDay=days;var instance={'@type':'CourseInstance','courseMode':p.id==='mos'?'online and onsite':'onsite','courseSchedule':schedule};if(p.location)instance.location={'@type':'Place','name':p.location};var prefix=locale==='de'?{s:'Situation: ',o:'Ergebnis: '}:(locale==='en'?{s:'Situation: ',o:'Outcome: '}:{s:'Helyzet: ',o:'Eredmény: '});var desc=[p.why,p.painPoint?prefix.s+p.painPoint:'',p.outcome?prefix.o+p.outcome:''].filter(Boolean).join(' ');var course={'@type':'Course','@id':'https://programvalaszto.magyariskola.at/'+(locale==='hu'?'foglalkozasok.html':locale+'/programs.html')+'#'+p.id,'name':p.name,'description':desc,'url':p.url,'inLanguage':locale==='de'?'de-AT':(locale==='en'?'en':'hu-AT'),'typicalAgeRange':ageLabel(p),'hasCourseInstance':instance};var provider=providerSchema(p);if(provider)course.provider=provider;if(p.relationship==='bmi-partner')course.additionalType='https://programvalaszto.magyariskola.at/#bmi-partner-program';return course}
function injectSchema(){var old=document.getElementById('catalog-schema');if(old)old.remove();var items=programs.map(function(p,i){return{'@type':'ListItem','position':i+1,'item':courseSchema(p)}});var graph={'@context':'https://schema.org','@graph':[{'@type':'EducationalOrganization','@id':'https://www.magyariskola.at/#org','name':'Bécsi Magyar Iskola','alternateName':['BMI','Wiener Ungarische Schule'],'url':'https://www.magyariskola.at','foundingDate':'1987-09','sameAs':['https://hu.wikipedia.org/wiki/B%C3%A9csi_Magyar_Iskola','https://www.magyariskola.at/tortenetunk']},{'@type':'ItemList','name':locale==='de'?'Programme der Wiener Ungarischen Schule und Partner 2026/2027':(locale==='en'?'Vienna Hungarian School and partner programs 2026/2027':'Bécsi Magyar Iskola és partnerprogramjai 2026/2027'),'numberOfItems':programs.length,'itemListElement':items}]};var s=document.createElement('script');s.id='catalog-schema';s.type='application/ld+json';s.textContent=JSON.stringify(graph);document.head.appendChild(s)}
function countMarkup(n){return n+' <span class="headline-accent">'+esc(tx.unit)+'</span>'}
function refreshStaticCount(){document.querySelectorAll('.hero .lead,.section-head p').forEach(function(el){el.innerHTML=el.innerHTML.replace(/\b26\b/g,String(programs.length)).replace(/\b25\b/g,String(programs.length))});var meta=document.querySelector('meta[name="description"]');if(meta)meta.content=meta.content.replace(/\b26\b/g,String(programs.length)).replace(/\b25\b/g,String(programs.length));}
function renderCatalog(){var list=document.getElementById('programList');if(!list)return;list.innerHTML=programs.map(card).join('');var count=document.getElementById('count');if(count)count.innerHTML=countMarkup(programs.length);var chips=document.querySelectorAll('#filters [data-filter]');chips.forEach(function(btn){btn.addEventListener('click',function(){chips.forEach(function(x){x.setAttribute('aria-pressed','false')});btn.setAttribute('aria-pressed','true');var f=btn.dataset.filter,n=0;list.querySelectorAll('.program-card').forEach(function(el){var weekdayMatch=(' '+el.dataset.weekdays+' ').indexOf(' '+f+' ')!==-1;var show=f==='all'||weekdayMatch||el.dataset.pace===f;el.hidden=!show;if(show)n++});if(count)count.innerHTML=countMarkup(n)})})}
function overlaps(p,min,max){return p.maxAge>=min&&p.minAge<=max}
function agePrograms(min,max){return programs.filter(function(p){return p.id!=='zenebona'&&overlaps(p,min,max)})}
function section(id,title,min,max){var arr=agePrograms(min,max);return'<section class="section" id="'+id+'"><div class="wrap"><div class="section-head"><div class="kicker">'+esc(title)+'</div><h2>'+arr.length+' <span class="headline-accent">'+esc(tx.unit)+'</span></h2></div><div class="list">'+arr.map(card).join('')+'</div></div></section>'}
function renderAges(){var root=document.getElementById('ageCatalog');if(!root)return;root.innerHTML=section('0-3','0–3 év',0,3)+section('3-6','3–6 év',3,6)+section('6-14','6–14 év',6,14)+section('14-17','14–17 év',14,17)+section('felnott','18+ / felnőtt',18,99)}
refreshStaticCount();injectSchema();renderCatalog();renderAges();
})();