(function(){
'use strict';
var cfg=window.BMI_FINDER;
if(!cfg||!Array.isArray(cfg.programs)||cfg.programs.length!==22)return;
var programs=cfg.programs;
function esc(s){return String(s).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function ageLabel(p){if(p.minAge===18&&p.maxAge===99)return 'Felnőtt';if(p.maxAge===99)return p.minAge+'+ év';return p.minAge+'–'+p.maxAge+' év'}
function weekdayLabel(v){return{hetfo:'Hétfő',kedd:'Kedd',szerda:'Szerda',csutortok:'Csütörtök',pentek:'Péntek',szombat:'Szombat',rugalmas:'Rugalmas'}[v]||v}
function schemaDay(v){return{hetfo:'https://schema.org/Monday',kedd:'https://schema.org/Tuesday',szerda:'https://schema.org/Wednesday',csutortok:'https://schema.org/Thursday',pentek:'https://schema.org/Friday',szombat:'https://schema.org/Saturday'}[v]||null}
function paceLabel(p){return p.pace==='rugalmas'?'Ritkább / rugalmasabb':'Rendszeres'}
function providerLabel(p){return p.provider==='BMI'?'Bécsi Magyar Iskola':p.provider}
function providerSchema(p){if(p.provider==='BMI')return {'@id':'https://www.magyariskola.at/#org'};var url=p.url;if(p.provider==='Napraforgók')url='https://napraforgok.at/';if(p.provider.indexOf('Cserkészcsapat')>-1)url='https://cserkesz.at/cserkesz-raj/';return {'@type':'Organization','name':p.provider,'url':url}}
function card(p){return '<article class="item program-card" id="'+esc(p.id)+'" data-day="'+esc(p.day)+'" data-weekday="'+esc(p.weekday)+'" data-pace="'+esc(p.pace)+'" data-min-age="'+p.minAge+'" data-max-age="'+p.maxAge+'"><h3><a href="'+esc(p.url)+'" target="_blank" rel="noopener">'+esc(p.name)+'</a></h3><div class="sub">'+esc(p.why)+'</div><div class="chips"><span class="chip age">'+esc(ageLabel(p))+'</span><span class="chip">'+esc(weekdayLabel(p.weekday))+'</span><span class="chip">'+esc(paceLabel(p))+'</span></div><ul class="kv"><li><span class="k">Mikor</span><span>'+esc(p.when)+'</span></li><li><span class="k">Programgazda</span><span>'+esc(providerLabel(p))+'</span></li></ul><p style="margin:14px 0 0"><a class="btn" href="'+esc(p.url)+'" target="_blank" rel="noopener">Részletek és jelentkezés</a></p></article>'}
function courseSchema(p){var schedule={'@type':'Schedule','repeatFrequency':p.pace==='rugalmas'?'Ritkább / rugalmasabb':'Rendszeres'};var day=schemaDay(p.weekday);if(day)schedule.byDay=[day];return {'@type':'Course','@id':'https://programvalaszto.magyariskola.at/foglalkozasok.html#'+p.id,'name':p.name,'description':p.why,'url':p.url,'inLanguage':'hu','provider':providerSchema(p),'typicalAgeRange':p.minAge+'-'+p.maxAge,'hasCourseInstance':{'@type':'CourseInstance','courseMode':'onsite','courseSchedule':schedule}}}
function injectSchema(){var old=document.getElementById('catalog-schema');if(old)old.remove();var items=programs.map(function(p,i){return {'@type':'ListItem','position':i+1,'item':courseSchema(p)}});var graph={'@context':'https://schema.org','@graph':[{'@type':'EducationalOrganization','@id':'https://www.magyariskola.at/#org','name':'Bécsi Magyar Iskola','alternateName':['BMI','Wiener Ungarische Schule'],'url':'https://www.magyariskola.at','foundingDate':'1987-09','sameAs':['https://hu.wikipedia.org/wiki/B%C3%A9csi_Magyar_Iskola','https://www.magyariskola.at/tortenetunk']},{'@type':'ItemList','name':'Bécsi Magyar Iskola foglalkozásai 2026/2027','numberOfItems':22,'itemListElement':items}]};var s=document.createElement('script');s.id='catalog-schema';s.type='application/ld+json';s.textContent=JSON.stringify(graph);document.head.appendChild(s)}
function renderCatalog(){var list=document.getElementById('programList');if(!list)return;list.innerHTML=programs.map(card).join('');var count=document.getElementById('count');if(count)count.textContent='22 foglalkozás';var chips=document.querySelectorAll('#filters [data-filter]');chips.forEach(function(btn){btn.addEventListener('click',function(){chips.forEach(function(x){x.setAttribute('aria-pressed','false')});btn.setAttribute('aria-pressed','true');var f=btn.dataset.filter,n=0;list.querySelectorAll('.program-card').forEach(function(el){var show=f==='all'||el.dataset.weekday===f||el.dataset.pace===f;el.hidden=!show;if(show)n++});if(count)count.textContent=n+' foglalkozás'})})}
function overlaps(p,min,max){return p.maxAge>=min&&p.minAge<=max}
function section(id,title,min,max){var arr=programs.filter(function(p){return overlaps(p,min,max)});return '<section class="section" id="'+id+'"><div class="wrap"><div class="section-head"><div class="kicker">'+esc(title)+'</div><h2>'+arr.length+' foglalkozás</h2></div><div class="list">'+arr.map(card).join('')+'</div></div></section>'}
function renderAges(){var root=document.getElementById('ageCatalog');if(!root)return;root.innerHTML=section('0-3','🍼 0–3 év',0,3)+section('3-6','🧸 3–6 év',3,6)+section('6-14','🎒 6–14 év',6,14)+section('14-21','🎧 14–21 év',14,21)+section('felnott','☕ Felnőtt',18,99)}
injectSchema();renderCatalog();renderAges();
})();