window.BMI_FINDER={
  sourcePolicy:{schoolYear:"2026/2027",canonicalOnly:true,excludePriorYearWix:true,verifiedFromCurrentLinks:true},
  interests:[
    {id:"nyelv",label:"Magyar nyelv és közösség"},
    {id:"alkotas",label:"Alkotás, művészet, színpad"},
    {id:"mozgas",label:"Mozgás, tánc, fejlesztés"},
    {id:"tech",label:"Technika, fotó, Minecraft"}
  ],
  days:[
    {id:"hetkoznap",label:"Hétköznap"},
    {id:"szombat",label:"Szombat"},
    {id:"mindegy",label:"Mindegy"}
  ],
  pace:[
    {id:"rendszeres",label:"Rendszeres program"},
    {id:"rugalmas",label:"Ritkább / rugalmasabb"},
    {id:"mindegy",label:"Mindegy"}
  ],
  programs:[
    {id:"borsofozde",name:"Borsófőzde | Schwedenplatz",minAge:0,maxAge:3,ageText:"babák és totyogók",interests:["nyelv","mozgas"],day:"hetkoznap",weekday:"hetfo",weekdays:["hetfo"],pace:"rendszeres",when:"Minden hétfőn 10:00 órától",location:"1010 Wien, Schwedenplatz 2.",teacher:"Horányi Bori, pszichopedagógus",fee:"40 € / hó",url:"https://www.magyariskola.at/event-details/borsofozde-2026",provider:"BMI",sourceType:"Wix Events 2026/27",why:"Zenés-mozgásos baba–mama közeg mondókákkal, énekkel és közösségi élménnyel."},
    {id:"ovoda",name:"Bécsi Magyar Óvoda | Schwedenplatz",minAge:3,maxAge:6,ageText:"óvodás korosztály",interests:["nyelv","alkotas","mozgas"],day:"szombat",weekday:"szombat",weekdays:["szombat"],pace:"rendszeres",when:"Szombatonként 10:00–12:00",location:"1010 Wien, Schwedenplatz 2.",teacher:"Bajka Kinga Csengele és Noszkó Niki",fee:"150 € / félév",url:"https://www.magyariskola.at/event-details/ovoda-2026",provider:"BMI",sourceType:"Wix Events 2026/27",why:"Magyar nyelv, körjáték, mese és alkotás óvodásoknak támogató magyar közösségben."},
    {id:"ovoda-baden",name:"Bécsi Magyar Óvoda | Baden",minAge:3,maxAge:6,ageText:"3–6 év",interests:["nyelv","alkotas","mozgas"],day:"hetkoznap",weekday:"csutortok",weekdays:["csutortok"],pace:"rendszeres",when:"Csütörtökönként 16:00–18:00",location:"Friedrich-Schiller-Platz 1, 2500 Baden",fee:"150 € / félév",firstDate:"2026. szeptember 17.",trial:"A jelentkezést követően próbaalkalom biztosított.",url:"https://www.magyariskola.at/event-details/ovoda-baden-2026",provider:"BMI",sourceType:"Wix Events 2026/27",why:"Magyar nyelvű óvodás közösség Badenben játékkal, mesével és kulturális kapcsolódással."},
    {id:"iskola-baden",name:"Magyar Iskola Badenben – „Ahol a magyar szó élménnyé válik”",minAge:7,maxAge:8,ageText:"7–8 év / 1–2. osztály",interests:["nyelv"],day:"hetkoznap",weekday:"kedd",weekdays:["kedd"],pace:"rendszeres",when:"Minden kedden 16:00–17:30",location:"Johannesgasse 9, 2500 Baden",fee:"60 € / hó vagy 300 € / félév",firstDate:"2026. szeptember 15.",trial:"Nyílt próbaalkalom: 2026. szeptember 8. 16:00.",url:"https://www.magyariskola.at/event-details/iskolabaden-2026",provider:"BMI",sourceType:"Wix Events 2026/27",why:"Játékos, mesés magyar nyelvi foglalkozás 1. és 2. osztályos gyermekeknek Badenben."},
    {id:"aspern",name:"Magyar nyelv tanítás | Aspern",minAge:6,maxAge:10,ageText:"6–10 év / 1–4. osztály",interests:["nyelv"],day:"hetkoznap",weekday:"kedd",weekdays:["kedd"],pace:"rendszeres",when:"Keddenként 15:30–17:00",location:"GTVS Wulzendorfstraße 1, 1220 Wien",teacher:"Schneider Erzsébet",fee:"180 € / félév",firstDate:"2026. szeptember 29.",trial:"Van lehetőség próbaalkalomra.",sourceNote:"A 2026/27-es Wix esemény strukturált időpontja 15:30–17:00, a leírás szövegében 15:45–17:15 is szerepel. A programválasztó a strukturált eseményidőpontot használja.",url:"https://www.magyariskola.at/event-details/magyaroktatas-kedd-2026",provider:"BMI",sourceType:"Wix Events 2026/27",why:"Kisiskolások magyar nyelvi fejlesztése játékos, családias közegben Aspernben."},
    {id:"seestadt",name:"Magyar nyelv tanítás | Seestadt",minAge:6,maxAge:10,ageText:"6–10 év / 1–4. osztály",interests:["nyelv"],day:"hetkoznap",weekday:"szerda",weekdays:["szerda"],pace:"rendszeres",when:"Szerdánként 16:00–17:30",location:"Bildungscampus könyvtár, Sonnenallee 116, 1220 Wien",teacher:"Dipl.-Päd. Schneider Erzsébet",fee:"180 € / félév",firstDate:"2026. szeptember 30.",trial:"Van lehetőség próbaalkalomra.",url:"https://www.magyariskola.at/event-details/magyarnyelv-szerda-2026",provider:"BMI",sourceType:"Wix Events 2026/27",why:"Magyar nyelv, játék, vers, ének és dramatizálás kisiskolásoknak Seestadtban."},
    {id:"schweden-1",name:"Magyar nyelv tanítás | Schwedenplatz | 1-es csoport",minAge:10,maxAge:14,ageText:"10–14 év",interests:["nyelv"],day:"szombat",weekday:"szombat",weekdays:["szombat"],pace:"rendszeres",when:"Kéthetente szombatonként 10:00–12:00",location:"1010 Wien, Schwedenplatz 2/8.",fee:"180 € / félév",firstDate:"2026. szeptember 19.",trial:"Van lehetőség próbaalkalomra.",url:"https://www.magyariskola.at/event-details/magyarnyelv-schwedenplatz-1",provider:"BMI",sourceType:"Wix Events 2026/27",why:"Magyar nyelv és kultúra 10–14 éveseknek, kis létszámú szombati csoportban."},
    {id:"schweden-2",name:"Magyar nyelv tanítás | Schwedenplatz | 2-es csoport",minAge:10,maxAge:14,ageText:"10–14 év",interests:["nyelv"],day:"szombat",weekday:"szombat",weekdays:["szombat"],pace:"rendszeres",when:"Kéthetente szombatonként 12:00–14:00",location:"1010 Wien, Schwedenplatz 2/8.",fee:"180 € / félév",firstDate:"2026. szeptember 19.",trial:"Van lehetőség próbaalkalomra.",url:"https://www.magyariskola.at/event-details/magyarnyelv-schwedenplatz-2",provider:"BMI",sourceType:"Wix Events 2026/27",why:"Magyar nyelv és kultúra 10–14 éveseknek a későbbi szombati idősávban."},
    {id:"alapozo",name:"Alapozó Terápia | Schwedenplatz",minAge:5,maxAge:10,ageText:"5–10 év",interests:["mozgas"],day:"hetkoznap",weekday:"kedd",weekdays:["kedd","csutortok"],pace:"rendszeres",when:"Kedden és csütörtökön 13:30–15:00",location:"1010 Wien, Schwedenplatz 2.",teacher:"Horányi Bori, gyógypedagógus, pszichopedagógus, mozgásterapeuta",fee:"270 € / 9 alkalmas bérlet (8 gyermekfoglalkozás + 1 szülőkonzultáció)",url:"https://www.magyariskola.at/event-details/alapozoterapia-2026",provider:"BMI",sourceType:"Wix Events 2026/27",why:"Kiscsoportos, mozgásalapú idegrendszeri fejlesztés 5–10 éves gyermekeknek."},
    {id:"rajztabla",name:"RAJZTÁBLA – Rajzfoglalkozás | Schwedenplatz",minAge:10,maxAge:18,ageText:"10+ éves gyerekeknek",interests:["alkotas"],day:"hetkoznap",weekday:"hetfo",weekdays:["hetfo"],pace:"rendszeres",when:"Minden hétfőn 16:30–18:00",location:"1010 Wien, Schwedenplatz 2.",teacher:"Boronkai Gabriella, tanító – vizuális nevelés szak",fee:"70 € / 4 alkalom",firstDate:"2026. szeptember 14.",sourceNote:"A 2026/27-es forrás 10+ éves gyerekeket nevez meg, felső korhatárt nem közöl. A kereső operatív felső határa 18 év.",url:"https://www.magyariskola.at/event-details/rajztabla-2026",provider:"BMI",sourceType:"Wix Events 2026/27",why:"Rajzi technika, kompozíció és árnyékolás 10 éves kortól, biztos vizuális alapokkal."},
    {id:"varazsceruza",name:"Varázsceruza | Schwedenplatz",minAge:9,maxAge:14,ageText:"9–14 év",interests:["alkotas"],day:"hetkoznap",weekday:"csutortok",weekdays:["csutortok"],pace:"rendszeres",when:"Csütörtökönként 16:30–18:00",location:"1010 Wien, Schwedenplatz 2/top 9",teacher:"Bajka Kinga Csengele",fee:"60 € / hónap",firstDate:"2026. szeptember 17.",trial:"Van lehetőség próbaalkalomra.",url:"https://www.magyariskola.at/event-details/varazsceruza-2026",provider:"BMI",sourceType:"Wix Events 2026/27",why:"Elmélyült kreatív alkotóműhely 9–14 éveseknek sokféle anyaggal és technikával."},
    {id:"becscraft",name:"BÉCS-CRAFT Workshop | Schwedenplatz",minAge:6,maxAge:15,ageText:"6–15 év",interests:["tech","alkotas"],day:"hetkoznap",weekday:"hetfo",weekdays:["hetfo"],pace:"rendszeres",when:"Hétfőnként 16:30–17:30 + havi helyszíni bejárás",location:"Bécsi Magyar Iskola, Schwedenplatz 2. Top 8.",teacher:"Korchma Zsombor",fee:"50 € / 5 alkalom / hó",firstDate:"2026. szeptember 21.",url:"https://www.magyariskola.at/event-details/becscraft-2026",provider:"BMI",sourceType:"Wix Events 2026/27",why:"Minecraft, építészet, történelem és helyszíni mérés egy közös bécsi projektben."},
    {id:"kicsi-svung",name:"Kicsi Svung – Dráma foglalkozás | Schwedenplatz",minAge:8,maxAge:13,ageText:"8–13 év",interests:["alkotas","nyelv"],day:"hetkoznap",weekday:"hetfo",weekdays:["hetfo"],pace:"rendszeres",when:"Hétfőnként 16:30–18:00",location:"1010 Wien, Schwedenplatz 2/top 9",teacher:"Bajka Kinga Csengele",fee:"60 € / hó",firstDate:"2026. szeptember 14.",trial:"Nincs lehetőség próbaalkalomra.",sourceNote:"A 2026/27-es Wix fő eseménymezői és részletes leírása hétfő 16:30–18:00, 8–13 év adatot közölnek; a legacy detailedDescription mezőben még csütörtök és 8–12 szerepel. A programválasztó a fő aktuális eseménymezőket használja.",url:"https://www.magyariskola.at/event-details/kicsisvung-2026",provider:"BMI",sourceType:"Wix Events 2026/27",why:"Színjátszás, improvizáció és magyar nyelvi önkifejezés 8–13 éves gyermekeknek."},
    {id:"mamut",name:"Bécsi Magyar Musical Társulat (MaMUT) – Musical Stúdió",minAge:7,maxAge:12,ageText:"7–12 év",interests:["alkotas","mozgas"],day:"hetkoznap",weekday:"csutortok",weekdays:["csutortok"],pace:"rendszeres",when:"Csütörtökönként 16:30–18:00",location:"Bécsi Magyar Iskola, Schwedenplatz 2, Top 8–9",teacher:"Hierholcz Anna és Pecze Ádám",fee:"60 € / hó vagy 300 € / félév",firstDate:"2026. szeptember 10. – nyílt óra",url:"https://www.magyariskola.at/event-details/mammut-2026",provider:"BMI",sourceType:"Wix Events 2026/27",why:"Ének, tánc és színpadi játék saját musical-projektekben, magyar nyelvi közegben."},
    {id:"gimi-svung",name:"Gimi Svung – Magyar nyelvű drámafoglalkozás | Schwedenplatz",minAge:12,maxAge:18,ageText:"gimnazistáknak",ageRangeOperational:true,interests:["alkotas","nyelv"],day:"hetkoznap",weekday:"pentek",weekdays:["pentek"],pace:"rendszeres",when:"Péntekenként 16:30–18:00",location:"Bécsi Magyar Iskola, 1010 Wien, Schwedenplatz 2/9.",fee:"70 € / fő / 4 alkalom",firstDate:"2026. szeptember 18.",sourceNote:"A 2026/27-es Wix-oldal 'gimnazistáknak' megjelölést használ konkrét életkori számsáv nélkül. A 12–18 év a kereső operatív sávja, nem a forrásból idézett korhatár.",url:"https://www.magyariskola.at/event-details/gimisvung-2026",provider:"BMI",sourceType:"Wix Events 2026/27",why:"Improvizáció, drámaírás és közös színpadi alkotás gimnazistáknak magyar nyelven."},
    {id:"filmes",name:"Filmes Műhely Workshop | Schwedenplatz",minAge:13,maxAge:17,ageText:"13–17 év",interests:["alkotas","tech"],day:"hetkoznap",weekday:"szerda",weekdays:["szerda"],pace:"rendszeres",when:"Minden szerdán 15:30–17:00",location:"Bécsi Magyar Iskola, Schwedenplatz – Nagyterem",teacher:"Dr. Trencsényi Klára DLA",fee:"60 € / hó",firstDate:"2026. szeptember 23.",url:"https://www.magyariskola.at/event-details/filmesmuhely-2026",provider:"BMI",sourceType:"Wix Events 2026/27",why:"Forgatókönyv, kamera, hang, rendezés és vágás egy teljes tanéves közös filmprojektben."},
    {id:"vilagfa",name:"Világfa Sárkányai | Schwedenplatz",minAge:6,maxAge:99,ageText:"gyermekrész + nyitott közös dobkör",interests:["nyelv","mozgas","alkotas"],day:"szombat",weekday:"szombat",weekdays:["szombat"],pace:"rugalmas",when:"Havonta egy szombat délután; gyermekrész + utána nyitott közös dobkör",url:"https://taltosdob.magyariskola.at",provider:"Regélő Fehér Táltos Hagyományőrző Egyesület",sourceType:"2026/27 saját programoldal",why:"Egyetlen program két egymásra épülő résszel: magyar eredetmondák és dobos gyermekfoglalkozás, majd nyitott közös dobkör."},
    {id:"napraforgocskak",name:"Napraforgócskák – Néptánc kicsiknek | Schwedenplatz",minAge:6,maxAge:14,ageText:"gyermekcsoport",interests:["mozgas","nyelv"],day:"hetkoznap",weekday:"szerda",weekdays:["szerda"],pace:"rendszeres",when:"Szerdánként 17:00–18:00",url:"https://napraforgok.at/r%C3%B3lunk#napraforgocskak",provider:"Napraforgók",sourceType:"partneroldal 2026/27",why:"Magyar gyermeknéptánc, zene és közösség a Napraforgók vezetésével."},
    {id:"cserkeszet",name:"Cserkészet | Alliiertenstrasse",minAge:5,maxAge:22,ageText:"5–22 év: kiscserkész, cserkész, vándor",interests:["nyelv","mozgas"],day:"szombat",weekday:"szombat",weekdays:["szombat"],pace:"rendszeres",when:"Kéthetente szombaton 16:00–19:00",location:"Alliiertenstrasse 2, 1020 Wien",url:"https://cserkesz.at/cserkesz-raj/",provider:"72. sz. Széchenyi István Cserkészcsapat",sourceType:"partneroldal 2026/27",why:"Kiscserkész, cserkész és vándor korosztály magyar közösségben, természetben és hagyományőrző programokon."},
    {id:"fotoklub",name:"Láss a Mesterek Szemével: VIPACH Felnőtt Fotóklub | Schwedenplatz",minAge:18,maxAge:99,ageText:"18+",interests:["tech","alkotas"],day:"hetkoznap",weekday:"csutortok",weekdays:["csutortok"],pace:"rendszeres",when:"Csütörtökönként 18:30–20:30",location:"1010 Wien, Schwedenplatz 2.",teacher:"Bánhalmi Norbert és Balogh Dávid",fee:"15 € / fő / alkalom",url:"https://www.magyariskola.at/event-details/fotoklub-2026",provider:"BMI",sourceType:"Wix Events 2026/27",why:"Fotográfiai látásmód, alkotás és technika felnőtteknek, művészeti és művészettörténeti vezetéssel."},
    {id:"fokusz",name:"FÓKUSZ-CSOPORT | Schwedenplatz",minAge:18,maxAge:99,ageText:"szülőknek / felnőtteknek",interests:["nyelv"],day:"hetkoznap",weekday:"rugalmas",weekdays:["rugalmas"],pace:"rugalmas",when:"A résztvevőkkel közösen egyeztetett sávokban",location:"1010 Wien, Schwedenplatz 2.",fee:"300 € / 10 alkalom (+ igény szerint 1 egyéni konzultáció)",url:"https://www.magyariskola.at/event-details/fokuszcsoport-2026",provider:"BMI",sourceType:"Wix Events 2026/27",why:"Homloklebeny-tréning fókuszhoz, tervezéshez, időgazdálkodáshoz és mentális egyensúlyhoz."},
    {id:"kezdo-neptanc",name:"Kezdő néptánc felnőtteknek | Schwedenplatz",minAge:16,maxAge:99,ageText:"felnőtt kezdő csoport",interests:["mozgas","nyelv"],day:"hetkoznap",weekday:"hetfo",weekdays:["hetfo"],pace:"rendszeres",when:"Hétfőnként 19:00–21:00",url:"https://napraforgok.at/r%C3%B3lunk#kezdocsoport",provider:"Napraforgók",sourceType:"partneroldal 2026/27",why:"Belépő szintű magyar néptánc felnőtteknek, közösségi formában."}
  ]
};