window.BMI_FINDER={
  sourcePolicy:{schoolYear:"2026/2027",canonicalOnly:true,excludePriorYearWix:true},
  interests:[
    {id:"nyelv",label:"Magyar nyelv és közösség"},
    {id:"alkotas",label:"Alkotás, művészet, színpad"},
    {id:"mozgas",label:"Mozgás, tánc, fejlesztés"},
    {id:"tech",label:"Technika, fotó, Minecraft"}
  ],
  days:[
    {id:"hetkoznap",label:"Hétköznap"},
    {id:"szombat",label:"Szombat"},
    {id:"mindegy",label:"Mindegy"}
  ],
  pace:[
    {id:"rendszeres",label:"Rendszeres program"},
    {id:"rugalmas",label:"Ritkább / rugalmasabb"},
    {id:"mindegy",label:"Mindegy"}
  ],
  programs:[
    {id:"borsofozde",name:"Borsófőzde",minAge:0,maxAge:3,interests:["nyelv","mozgas"],day:"hetkoznap",weekday:"hetfo",pace:"rendszeres",when:"Hétfőnként 10:00-tól",url:"https://www.magyariskola.at/event-details/borsofozde-2026",provider:"BMI",why:"Baba–mama közeg, magyar mondókák, ének és játékos mozgás."},
    {id:"ovoda",name:"Bécsi Magyar Óvoda | Schwedenplatz",minAge:3,maxAge:6,interests:["nyelv","alkotas","mozgas"],day:"szombat",weekday:"szombat",pace:"rendszeres",when:"Szombaton 10:00–12:00",url:"https://www.magyariskola.at/event-details/ovoda-2026",provider:"BMI",why:"Magyar nyelv, mese, játék és alkotás óvodásoknak."},
    {id:"ovoda-baden",name:"Bécsi Magyar Óvoda | Baden",minAge:3,maxAge:6,interests:["nyelv","alkotas","mozgas"],day:"hetkoznap",weekday:"csutortok",pace:"rendszeres",when:"Csütörtökön 16:00–18:00",url:"https://www.magyariskola.at/event-details/ovoda-baden-2026",provider:"BMI",why:"Magyar óvodai közösség Badenben, mesével, dallal és játékos foglalkozásokkal."},
    {id:"iskola-baden",name:"Magyar Iskola Badenben",minAge:6,maxAge:9,interests:["nyelv"],day:"hetkoznap",weekday:"kedd",pace:"rendszeres",when:"Keddenként 16:00–17:30",url:"https://www.magyariskola.at/event-details/iskolabaden-2026",provider:"BMI",why:"Olvasás, szókincs és szövegértés kétnyelvű környezetben."},
    {id:"aspern",name:"Magyar nyelv tanítás | Aspern",minAge:6,maxAge:10,interests:["nyelv"],day:"hetkoznap",weekday:"kedd",pace:"rendszeres",when:"Keddenként 15:30–17:00",url:"https://www.magyariskola.at/event-details/magyaroktatas-kedd-2026",provider:"BMI",why:"Kisiskolások magyar nyelvi fejlesztése játékos, személyre szabott feladatokkal."},
    {id:"seestadt",name:"Magyar nyelv tanítás | Seestadt",minAge:6,maxAge:10,interests:["nyelv"],day:"hetkoznap",weekday:"szerda",pace:"rendszeres",when:"Szerdánként 16:00–17:30",url:"https://www.magyariskola.at/event-details/magyarnyelv-szerda-2026",provider:"BMI",why:"Magyar nyelv, játék, vers, ének és dramatizálás Seestadtban."},
    {id:"schweden-1",name:"Magyar nyelv tanítás | Schwedenplatz | 1-es csoport",minAge:6,maxAge:10,interests:["nyelv"],day:"szombat",weekday:"szombat",pace:"rendszeres",when:"Kéthetente szombaton 10:00–11:30",url:"https://www.magyariskola.at/event-details/magyarnyelv-schwedenplatz-1",provider:"BMI",why:"Szókincsbővítés és magabiztos magyar nyelvhasználat közösségben."},
    {id:"schweden-2",name:"Magyar nyelv tanítás | Schwedenplatz | 2-es csoport",minAge:6,maxAge:10,interests:["nyelv"],day:"szombat",weekday:"szombat",pace:"rendszeres",when:"Kéthetente szombaton 12:00–13:30",url:"https://www.magyariskola.at/event-details/magyarnyelv-schwedenplatz-2",provider:"BMI",why:"A schwedenplatzi magyar nyelvi program későbbi szombati idősávban."},
    {id:"alapozo",name:"Alapozó Terápia | Schwedenplatz",minAge:5,maxAge:8,interests:["mozgas"],day:"hetkoznap",weekday:"hetfo",pace:"rendszeres",when:"Hétfőnként 14:30–15:30",url:"https://www.magyariskola.at/event-details/alapozoterapia-2026",provider:"BMI",why:"Mozgásalapú idegrendszeri fejlesztés kis létszámú csoportban."},
    {id:"rajztabla",name:"RAJZTÁBLA – Rajzfoglalkozás | Schwedenplatz",minAge:10,maxAge:18,interests:["alkotas"],day:"szombat",weekday:"szombat",pace:"rugalmas",when:"Szombaton 14:00–15:30, havonta 1–2 alkalom",url:"https://www.magyariskola.at/event-details/rajztabla-2026",provider:"BMI",why:"Rajzi technika, kompozíció és árnyékolás 10 éves kortól."},
    {id:"varazsceruza",name:"Varázsceruza | Schwedenplatz",minAge:6,maxAge:12,interests:["alkotas"],day:"hetkoznap",weekday:"csutortok",pace:"rendszeres",when:"Csütörtökön 16:30–18:00",url:"https://www.magyariskola.at/event-details/varazsceruza-2026",provider:"BMI",why:"Elmélyült kreatív alkotóműhely sokféle anyaggal és technikával."},
    {id:"becscraft",name:"BÉCS-CRAFT Workshop | Schwedenplatz",minAge:6,maxAge:15,interests:["tech","alkotas"],day:"hetkoznap",weekday:"hetfo",pace:"rendszeres",when:"Hétfőnként 16:30–17:30 + havi helyszíni bejárás",url:"https://www.magyariskola.at/event-details/becscraft-2026",provider:"BMI",why:"Minecraft, építészet, történelem és mérés egy közös projektben."},
    {id:"kicsi-svung",name:"Kicsi Svung – Dráma foglalkozás | Schwedenplatz",minAge:6,maxAge:12,interests:["alkotas","nyelv"],day:"hetkoznap",weekday:"hetfo",pace:"rendszeres",when:"Hétfőn 16:30–18:00",url:"https://www.magyariskola.at/event-details/kicsisvung-2026",provider:"BMI",why:"Színjátszás, improvizáció és magyar nyelvi önkifejezés gyerekeknek."},
    {id:"mamut",name:"Bécsi Magyar Musical Társulat (maMUT) – Musical Stúdió",minAge:8,maxAge:13,interests:["alkotas","mozgas"],day:"hetkoznap",weekday:"csutortok",pace:"rendszeres",when:"Csütörtökön 16:30–18:00",url:"https://www.magyariskola.at/event-details/mammut-2026",provider:"BMI",why:"Ének, mozgás és színpadi játék musical-projektekben."},
    {id:"gimi-svung",name:"Gimi Svung – Magyar nyelvű drámafoglalkozás",minAge:12,maxAge:18,interests:["alkotas","nyelv"],day:"hetkoznap",weekday:"pentek",pace:"rendszeres",when:"Péntekenként 16:30–18:00",url:"https://www.magyariskola.at/event-details/gimisvung-2026",provider:"BMI",why:"Improvizáció, drámaírás és saját színpadi produkció gimnazistáknak."},
    {id:"filmes",name:"Filmes Műhely Workshop | Schwedenplatz",minAge:13,maxAge:17,interests:["alkotas","tech"],day:"hetkoznap",weekday:"szerda",pace:"rendszeres",when:"Szerdánként 15:15–16:45",url:"https://www.magyariskola.at/event-details/filmesmuhely-2026",provider:"BMI",why:"Forgatókönyv, kamera, hang, rendezés és vágás egy közös film elkészítéséig."},
    {id:"vilagfa",name:"Világfa Sárkányai | Schwedenplatz",minAge:6,maxAge:99,interests:["nyelv","mozgas","alkotas"],day:"szombat",weekday:"szombat",pace:"rugalmas",when:"Havonta egy szombat délután; gyermekrész + utána nyitott közös dobkör",url:"https://taltosdob.magyariskola.at",provider:"Regélő Fehér Táltos Hagyományőrző Egyesület",why:"Egyetlen program két egymásra épülő résszel: magyar eredetmondák és dobos gyermekfoglalkozás, majd nyitott közös dobkör."},
    {id:"napraforgocskak",name:"Napraforgócskák – Néptánc kicsiknek | Schwedenplatz",minAge:6,maxAge:14,interests:["mozgas","nyelv"],day:"hetkoznap",weekday:"szerda",pace:"rendszeres",when:"Szerdánként 17:00–18:00",url:"https://napraforgok.at/r%C3%B3lunk#napraforgocskak",provider:"Napraforgók",why:"Magyar gyermeknéptánc, zene és közösség a Napraforgók vezetésével."},
    {id:"cserkeszet",name:"Cserkészet | Alliiertenstrasse",minAge:5,maxAge:22,interests:["nyelv","mozgas"],day:"szombat",weekday:"szombat",pace:"rendszeres",when:"Kéthetente szombaton 16:00–19:00",url:"https://cserkesz.at/cserkesz-raj/",provider:"72. sz. Széchenyi István Cserkészcsapat",why:"Kiscserkész, cserkész és vándor korosztály magyar közösségben, természetben és hagyományőrző programokon."},
    {id:"fotoklub",name:"Láss a Mesterek Szemével: VIPACH Felnőtt Fotóklub",minAge:18,maxAge:99,interests:["tech","alkotas"],day:"hetkoznap",weekday:"csutortok",pace:"rendszeres",when:"Csütörtökön 18:30–20:30",url:"https://www.magyariskola.at/event-details/fotoklub-2026",provider:"BMI",why:"Fotográfiai látásmód, alkotás és technika felnőtteknek."},
    {id:"fokusz",name:"FÓKUSZ-CSOPORT | Schwedenplatz",minAge:18,maxAge:99,interests:["nyelv"],day:"hetkoznap",weekday:"rugalmas",pace:"rugalmas",when:"75 perces alkalmak, egyeztetett időpontban",url:"https://www.magyariskola.at/event-details/fokuszcsoport-2026",provider:"BMI",why:"Figyelem, tervezés, érzelemszabályozás és önirányítás felnőtteknek."},
    {id:"kezdo-neptanc",name:"Kezdő néptánc felnőtteknek | Schwedenplatz",minAge:16,maxAge:99,interests:["mozgas","nyelv"],day:"hetkoznap",weekday:"hetfo",pace:"rendszeres",when:"Hétfőnként 19:00–21:00",url:"https://napraforgok.at/r%C3%B3lunk#kezdocsoport",provider:"Napraforgók",why:"Belépő szintű magyar néptánc felnőtteknek, közösségi formában."}
  ]
};