window.BMI_FINDER={
  sourcePolicy:{schoolYear:"2026/2027",canonicalOnly:true,excludePriorYearWix:true,verifiedFromCurrentLinks:true},
  interests:[
    {id:"nyelv",label:"Magyar nyelv és közösség"},
    {id:"alkotas",label:"Alkotás, művészet, színpad"},
    {id:"mozgas",label:"Mozgás, tánc, fejlesztés"},
    {id:"tech",label:"Technika, Office, fotó, Minecraft"},
    {id:"logika",label:"Logika, sakk, stratégia"}
  ],
  days:[
    {id:"hetkoznap",label:"Hétköznap"},
    {id:"szombat",label:"Szombat"},
    {id:"mindegy",label:"Mindegy"}
  ],
  pace:[
    {id:"rendszeres",label:"Rendszeres program"},
    {id:"rugalmas",label:"Ritkább / rugalmasabb"},
    {id:"mindegy",label:"Mindegy"}
  ],
  programs:[
    {id:"borsofozde",name:"Borsófőzde | Schwedenplatz",minAge:0,maxAge:3,ageText:"babák és totyogók",interests:["nyelv","mozgas"],day:"hetkoznap",weekday:"hetfo",weekdays:["hetfo"],pace:"rendszeres",when:"Minden hétfőn 10:00 órától",location:"Schwedenplatz 2., 1010 Wien – 9-es terem",teacher:"Horányi Bori, pszichopedagógus",fee:"40 € / hó",firstDate:"2026. szeptember 14.",url:"https://www.magyariskola.at/event-details/borsofozde-2026",provider:"BMI",sourceType:"Wix Events 2026/27",why:"Zenés-mozgásos baba–mama közeg mondókákkal, énekkel és közösségi élménnyel."},
    {id:"ovoda",name:"Bécsi Magyar Óvoda | Schwedenplatz",minAge:3,maxAge:6,ageText:"óvodás korosztály",interests:["nyelv","alkotas","mozgas"],day:"szombat",weekday:"szombat",weekdays:["szombat"],pace:"rendszeres",when:"Szombatonként 10:00–12:00",location:"Schwedenplatz 2/top 9, 1010 Wien",teacher:"Bajka Kinga Csengele és Noszkó Niki",fee:"150 € / félév",trial:"Új érdeklődőknek egy próbaóra lehetséges.",url:"https://www.magyariskola.at/event-details/ovoda-2026",provider:"BMI",sourceType:"Wix Events 2026/27",why:"Magyar nyelv, körjáték, mese és alkotás óvodásoknak támogató magyar közösségben."},
    {id:"ovoda-baden",name:"Bécsi Magyar Óvoda | Baden",minAge:3,maxAge:6,ageText:"3–6 év",interests:["nyelv","alkotas","mozgas"],day:"hetkoznap",weekday:"csutortok",weekdays:["csutortok"],pace:"rendszeres",when:"Csütörtökönként 16:00–18:00",location:"Friedrich-Schiller-Platz 1, 2500 Baden",fee:"150 € / félév",firstDate:"2026. szeptember 17.",trial:"A jelentkezést követően próbaalkalom biztosított.",url:"https://www.magyariskola.at/event-details/ovoda-baden-2026",provider:"BMI",sourceType:"Wix Events 2026/27",why:"Magyar nyelvű óvodás közösség Badenben játékkal, mesével és kulturális kapcsolódással."},
    {id:"iskola-baden",name:"Magyar Iskola Badenben – „Ahol a magyar szó élménnyé válik”",minAge:7,maxAge:8,ageText:"7–8 év / 1–2. osztály",interests:["nyelv"],day:"hetkoznap",weekday:"kedd",weekdays:["kedd"],pace:"rendszeres",when:"Minden kedden 16:00–17:30",location:"Johannesgasse 9, 2500 Baden",teacher:"Makfalvi Rita, óvodapedagógus, tanító, nyelv- és beszédfejlesztő pedagógus",fee:"60 € / hó vagy 300 € / félév",firstDate:"2026. szeptember 15.",trial:"Nyílt próbaalkalom: 2026. szeptember 8. 16:00.",url:"https://www.magyariskola.at/event-details/iskolabaden-2026",provider:"BMI",sourceType:"Wix Events 2026/27",why:"Játékos, mesés magyar nyelvi foglalkozás 1. és 2. osztályos gyermekeknek Badenben."},
    {id:"aspern",name:"Magyar nyelv tanítás | Aspern",minAge:6,maxAge:10,ageText:"6–10 év / 1–4. osztály",interests:["nyelv"],day:"hetkoznap",weekday:"kedd",weekdays:["kedd"],pace:"rendszeres",when:"Keddenként 15:30–17:00",location:"GTVS Wulzendorfstraße 1, 1220 Wien – zöld csoportszoba",teacher:"Schneider Erzsébet",fee:"180 € / félév",firstDate:"2026. szeptember 29.",trial:"Van lehetőség próbaalkalomra.",url:"https://www.magyariskola.at/event-details/magyaroktatas-kedd-2026",provider:"BMI",sourceType:"Wix Events 2026/27",why:"Kisiskolások magyar nyelvi fejlesztése játékos, családias közegben Aspernben."},
    {id:"seestadt",name:"Magyar nyelv tanítás | Seestadt",minAge:6,maxAge:10,ageText:"6–10 év / 1–4. osztály",interests:["nyelv"],day:"hetkoznap",weekday:"szerda",weekdays:["szerda"],pace:"rendszeres",when:"Szerdánként 16:00–17:30",location:"Bildungscampus könyvtár, Sonnenallee 116, 1220 Wien",teacher:"Dipl.-Päd. Schneider Erzsébet",fee:"180 € / félév",firstDate:"2026. szeptember 30.",trial:"Van lehetőség próbaalkalomra.",url:"https://www.magyariskola.at/event-details/magyarnyelv-szerda-2026",provider:"BMI",sourceType:"Wix Events 2026/27",why:"Magyar nyelv, játék, vers, ének és dramatizálás kisiskolásoknak Seestadtban."},
    {id:"schweden-1",name:"Magyar nyelv tanítás | Schwedenplatz | 1-es csoport",minAge:6,maxAge:10,ageText:"6–10 év",interests:["nyelv"],day:"szombat",weekday:"szombat",weekdays:["szombat"],pace:"rendszeres",when:"Kéthetente szombatonként 10:00–12:00",location:"Schwedenplatz 2/8., 1010 Wien",teacher:"Kiss Ágnes",fee:"180 € / félév",firstDate:"2026. szeptember 19.",trial:"Van lehetőség próbaalkalomra.",url:"https://www.magyariskola.at/event-details/magyarnyelv-schwedenplatz-1",provider:"BMI",sourceType:"Wix Events 2026/27",why:"Magyar nyelv és kultúra 6–10 éveseknek, kis létszámú szombati csoportban."},
    {id:"schweden-2",name:"Magyar nyelv tanítás | Schwedenplatz | 2-es csoport",minAge:10,maxAge:14,ageText:"10–14 év",interests:["nyelv"],day:"szombat",weekday:"szombat",weekdays:["szombat"],pace:"rendszeres",when:"Kéthetente szombatonként 12:00–14:00",location:"Schwedenplatz 2/8., 1010 Wien",teacher:"Kiss Ágnes",fee:"180 € / félév",firstDate:"2026. szeptember 19.",trial:"Van lehetőség próbaalkalomra.",url:"https://www.magyariskola.at/event-details/magyarnyelv-schwedenplatz-2",provider:"BMI",sourceType:"Wix Events 2026/27",why:"Magyar nyelv és kultúra 10–14 éveseknek a későbbi szombati idősávban."},
    {id:"alapozo",name:"Alapozó Terápia | Schwedenplatz",minAge:5,maxAge:10,ageText:"5–10 év",interests:["mozgas"],day:"hetkoznap",weekday:"kedd",weekdays:["kedd","csutortok"],pace:"rendszeres",when:"Kedden és csütörtökön 13:30–15:00",location:"Schwedenplatz 2., 1010 Wien",teacher:"Horányi Bori, gyógypedagógus, pszichopedagógus, mozgásterapeuta",fee:"270 € / 9 alkalmas bérlet (8 gyermekfoglalkozás + 1 szülőkonzultáció)",firstDate:"2026. szeptember 15.",url:"https://www.magyariskola.at/event-details/alapozoterapia-2026",provider:"BMI",sourceType:"Wix Events 2026/27",why:"Kiscsoportos, mozgásalapú idegrendszeri fejlesztés 5–10 éves gyermekeknek."},
    {id:"rajztabla",name:"RAJZTÁBLA – Rajzfoglalkozás | Schwedenplatz",minAge:10,maxAge:18,ageText:"10+ éves gyerekeknek",interests:["alkotas"],day:"hetkoznap",weekday:"hetfo",weekdays:["hetfo"],pace:"rendszeres",when:"Minden hétfőn 16:30–18:00",location:"Schwedenplatz 2., 1010 Wien",teacher:"Boronkai Gabriella, tanító – vizuális nevelés szak",fee:"70 € / 4 alkalom",firstDate:"2026. szeptember 14.",sourceNote:"A 2026/27-es forrás 10+ éves gyerekeket nevez meg, felső korhatárt nem közöl. A kereső operatív felső határa 18 év.",url:"https://www.magyariskola.at/event-details/rajztabla-2026",provider:"BMI",sourceType:"Wix Events 2026/27",why:"Rajzi technika, kompozíció és árnyékolás 10 éves kortól, biztos vizuális alapokkal."},
    {id:"varazsceruza",name:"Varázsceruza | Schwedenplatz",minAge:9,maxAge:14,ageText:"9–14 év",interests:["alkotas"],day:"hetkoznap",weekday:"csutortok",weekdays:["csutortok"],pace:"rendszeres",when:"Csütörtökönként 16:30–18:00",location:"Schwedenplatz 2/top 9, 1010 Wien",teacher:"Bajka Kinga Csengele",fee:"60 € / hónap",firstDate:"2026. szeptember 17.",trial:"Van lehetőség próbaalkalomra.",url:"https://www.magyariskola.at/event-details/varazsceruza-2026",provider:"BMI",sourceType:"Wix Events 2026/27",why:"Elmélyült kreatív alkotóműhely 9–14 éveseknek sokféle anyaggal és technikával."},
    {id:"becscraft",name:"BÉCS-CRAFT Workshop | Schwedenplatz",minAge:6,maxAge:15,ageText:"6–15 év",interests:["tech","alkotas"],day:"hetkoznap",weekday:"hetfo",weekdays:["hetfo"],pace:"rendszeres",when:"Hétfőnként 16:30–17:30 + havi helyszíni bejárás",location:"Bécsi Magyar Iskola, Schwedenplatz 2. Top 8.",teacher:"Korchma Zsombor",fee:"50 € / 5 alkalom / hó",firstDate:"2026. szeptember 21.",url:"https://www.magyariskola.at/event-details/becscraft-2026",provider:"BMI",sourceType:"Wix Events 2026/27",why:"Minecraft, építészet, történelem és helyszíni mérés egy közös bécsi projektben."},
    {id:"kicsi-svung",name:"Kicsi Svung – Dráma foglalkozás | Schwedenplatz",minAge:8,maxAge:13,ageText:"8–13 év",interests:["alkotas","nyelv"],day:"hetkoznap",weekday:"hetfo",weekdays:["hetfo"],pace:"rendszeres",when:"Hétfőnként 16:30–18:00",location:"Schwedenplatz 2/top 9, 1010 Wien",teacher:"Bajka Kinga Csengele",fee:"60 € / hó",firstDate:"2026. szeptember 14.",trial:"Nincs lehetőség próbaalkalomra.",url:"https://www.magyariskola.at/event-details/kicsisvung-2026",provider:"BMI",sourceType:"Wix Events 2026/27",why:"Színjátszás, improvizáció és magyar nyelvi önkifejezés 8–13 éves gyermekeknek."},
    {id:"mamut",name:"Bécsi Magyar Musical Társulat (MaMUT) – Musical Stúdió",minAge:7,maxAge:12,ageText:"7–12 év",interests:["alkotas","mozgas"],day:"hetkoznap",weekday:"csutortok",weekdays:["csutortok"],pace:"rendszeres",when:"Csütörtökönként 16:30–18:00",location:"Bécsi Magyar Iskola, Schwedenplatz 2, Top 8–9",teacher:"Hierholcz Anna és Pecze Ádám",fee:"60 € / hó vagy 300 € / félév",firstDate:"2026. szeptember 10. – nyílt óra",trial:"Kezdőknek próbaalkalom / személyes találkozó kérhető.",url:"https://www.magyariskola.at/event-details/mammut-2026",provider:"BMI",sourceType:"Wix Events 2026/27",why:"Ének, tánc és színpadi játék saját musical-projektekben, magyar nyelvi közegben."},
    {id:"gimi-svung",name:"Gimi Svung – Magyar nyelvű drámafoglalkozás | Schwedenplatz",minAge:12,maxAge:18,ageText:"gimnazistáknak",ageRangeOperational:true,interests:["alkotas","nyelv"],day:"hetkoznap",weekday:"pentek",weekdays:["pentek"],pace:"rendszeres",when:"Péntekenként 16:30–18:00",location:"Bécsi Magyar Iskola, 1010 Wien, Schwedenplatz 2/9.",fee:"70 € / fő / 4 alkalom",firstDate:"2026. szeptember 18.",sourceNote:"A 2026/27-es Wix-oldal 'gimnazistáknak' megjelölést használ konkrét életkori számsáv nélkül. A 12–18 év a kereső operatív sávja, nem a forrásból idézett korhatár.",url:"https://www.magyariskola.at/event-details/gimisvung-2026",provider:"BMI",sourceType:"Wix Events 2026/27",why:"Improvizáció, drámaírás és közös színpadi alkotás gimnazistáknak magyar nyelven."},
    {id:"filmes",name:"Filmes Műhely Workshop | Schwedenplatz",minAge:13,maxAge:17,ageText:"13–17 év",interests:["alkotas","tech"],day:"hetkoznap",weekday:"szerda",weekdays:["szerda"],pace:"rendszeres",when:"Minden szerdán 15:30–17:00",location:"Bécsi Magyar Iskola, Schwedenplatz – Nagyterem",teacher:"Dr. Trencsényi Klára DLA",fee:"60 € / hó",firstDate:"2026. szeptember 23.",url:"https://www.magyariskola.at/event-details/filmesmuhely-2026",provider:"BMI",sourceType:"Wix Events 2026/27",why:"Forgatókönyv, kamera, hang, rendezés és vágás egy teljes tanéves közös filmprojektben."},
    {id:"sakk",name:"Sakk és Gondolkodásfejlesztés | Schwedenplatz",minAge:6,maxAge:99,ageText:"6 éves kortól 99 éves korig",interests:["logika"],day:"szombat",weekday:"szombat",weekdays:["szombat"],pace:"rugalmas",when:"Havonta 1 alkalommal, szombatonként 13:00–15:00",location:"Bécsi Magyar Iskola, Schwedenplatz 2, Top 8 (TV-s terem)",teacher:"Fersztl Barnabás",teacherContact:"+36 30 629 4825",fee:"6–14 év: 20 € / fő / óra; 14 év felett: 25 € / fő / óra; próbaalkalom: 10 €",firstDate:"2026. szeptember 26.",registrationDeadline:"2026. szeptember 25.",capacity:"Maximum 16 fő",url:"https://www.magyariskola.at/event-details/sakk-2026",provider:"BMI",sourceType:"Wix Events 2026/27",why:"Sakkfeladványok, taktikai megnyitások és játszmák a logika, stratégiai gondolkodás és koncentráció fejlesztésére."},
    {id:"fecskeklub",name:"Fecske Klub | Schwedenplatz",minAge:8,maxAge:18,ageText:"8 éves kortól, iskolás korosztálynak",ageRangeOperational:true,interests:["nyelv","alkotas"],day:"hetkoznap",weekday:"kedd",weekdays:["kedd"],pace:"rendszeres",when:"Keddenként 16:30–18:00; 1 × 90 perc",period:"2026. október 20. – 2027. január 26.",location:"Bécsi Magyar Iskola – Schwedenplatz, 1010 Bécs, Schwedenplatz 2/8.",teacher:"Falusi Dóra",teacherContact:"+43 660 9725 359 · dora.falusi@fecskeklub.at",fee:"52 € / hó vagy 187 € / félév",firstDate:"2026. október 20.",registrationDeadline:"2026. október 9.",capacity:"Minimum 6 gyermek; felső létszámkorlát nincs meghatározva",trial:"Ingyenes próbaóra: 2026. október 13., 16:30–18:00",sourceNote:"A hivatalos Wix-eseményoldal iskolás korosztályt nevez meg számszerű korhatár nélkül; a Fecske Klub saját oldala 8 éves kortól ajánlja a programot. A 8–18 év a programválasztó dokumentált operatív keresési sávja, nem közzétett felső korhatár.",url:"https://www.magyariskola.at/event-details/fecskeklub-2026",provider:"BMI",sourceType:"Wix Events 2026/27",why:"Játékos, képekkel és rövid videókkal kísért magyar kultúrtörténeti felfedezés, beszélgetéssel és kreatív alkotással."},
    {id:"vilagfa",name:"Világfa Sárkányai | Schwedenplatz",minAge:6,maxAge:99,ageText:"6–14 éves gyermekrész + utána nyitott felnőtt dzsemelés",ageRangeComposite:true,interests:["nyelv","mozgas","alkotas"],day:"szombat",weekday:"szombat",weekdays:["szombat"],pace:"rugalmas",when:"Havi 1 alkalom, jellemzően szombatonként 16:00-tól; az első félév szeptembertől februárig tart",location:"Schwedenplatz 2. / Laurenzerberg 5., 1010 Wien",teacher:"Hupczik Andrea",fee:"70 € / fő / félév; a második félév szintén 70 € / fő",enrollment:"Bármikor be lehet csatlakozni.",firstDate:"2026. szeptember 27. (vasárnap)",sourceNote:"Az első félév szeptembertől februárig tart, hozzájárulási díja 70 € / fő. A második félév hozzájárulási díja szintén 70 € / fő, és a programhoz bármikor be lehet csatlakozni. Az első bemutató alkalom kivételesen vasárnap, 2026. szeptember 27-én lesz; a havi alkalmak jellemzően szombatonként 16:00-kor kezdődnek.",url:"https://taltosdob.magyariskola.at",provider:"Regélő Fehér Táltos Hagyományőrző Egyesület",sourceType:"2026/27 saját programoldal",why:"6–14 éves gyermek dobcsapat magyar néphagyománnyal, közös dobolással és történetekkel; minden alkalom után nyitott felnőtt dzsemelés, folyamatos csatlakozási lehetőséggel."},
    {id:"napraforgocskak",name:"Napraforgócskák – Néptánc kicsiknek | Schwedenplatz",minAge:6,maxAge:14,ageText:"gyermekcsoport – a partneroldal nem közöl számszerű korhatárt",ageRangeOperational:true,interests:["mozgas","nyelv"],day:"hetkoznap",weekday:"szerda",weekdays:["szerda"],pace:"rendszeres",when:"Szerdánként 17:00–18:00; kéthetente Badenben is van hosszabb alkalom",location:"Bécsi Magyar Iskola, Schwedenplatz 2 / Laurenzerberg 5., 1010 Wien, Top 8",teacher:"Varga Bernadette és Veres Tamás",sourceNote:"A partneroldal gyermekcsoportként írja le a Napraforgócskákat, de aktuálisan nem közöl számszerű korhatárt. A 6–14 év a programválasztó operatív keresési sávja.",url:"https://napraforgok.at/r%C3%B3lunk#napraforgocskak",provider:"Napraforgók",sourceType:"partneroldal 2026/27",why:"Magyar gyermeknéptánc, zene és közösség a Napraforgók vezetésével."},
    {id:"cserkeszet",name:"Cserkészet | Alliiertenstrasse",minAge:5,maxAge:22,ageText:"5–22 év: kiscserkész 5–10, cserkész 10–16, vándor 17–22",interests:["nyelv","mozgas"],day:"szombat",weekday:"szombat",weekdays:["szombat"],pace:"rendszeres",when:"Kéthetente szombaton 16:00–19:00",location:"Alliiertenstrasse 2, 1020 Wien",url:"https://cserkesz.at/cserkesz-raj/",provider:"72. sz. Széchenyi István Cserkészcsapat",sourceType:"partneroldal 2026/27",why:"Kiscserkész, cserkész és vándor korosztály magyar közösségben, természetben és hagyományőrző programokon."},
    {id:"fotoklub",name:"Láss a Mesterek Szemével: VIPACH Felnőtt Fotóklub | Schwedenplatz",minAge:18,maxAge:99,ageText:"18+",interests:["tech","alkotas"],day:"hetkoznap",weekday:"csutortok",weekdays:["csutortok"],pace:"rendszeres",when:"Csütörtökönként 18:30–20:30",location:"Schwedenplatz 2., 1010 Wien",teacher:"Bánhalmi Norbert és Balogh Dávid",fee:"15 € / fő / alkalom",url:"https://www.magyariskola.at/event-details/fotoklub-2026",provider:"BMI",sourceType:"Wix Events 2026/27",why:"Fotográfiai látásmód, alkotás és technika felnőtteknek, művészeti és művészettörténeti vezetéssel."},
    {id:"fokusz",name:"FÓKUSZ-CSOPORT | Schwedenplatz",minAge:18,maxAge:99,ageText:"szülőknek / felnőtteknek",interests:["nyelv"],day:"hetkoznap",weekday:"rugalmas",weekdays:["rugalmas"],pace:"rugalmas",when:"A résztvevőkkel közösen egyeztetett sávokban; 10 alkalom kéthetente, 75 perc / alkalom",location:"Schwedenplatz 2., 1010 Wien",teacher:"Horányi Bori, pszichopedagógus",fee:"300 € / 10 alkalom (+ igény szerint 1 egyéni konzultáció)",url:"https://www.magyariskola.at/event-details/fokuszcsoport-2026",provider:"BMI",sourceType:"Wix Events 2026/27",why:"Homloklebeny-tréning fókuszhoz, tervezéshez, időgazdálkodáshoz és mentális egyensúlyhoz."},
    {id:"kezdo-neptanc",name:"Kezdő néptánc felnőtteknek | Schwedenplatz",minAge:18,maxAge:99,ageText:"felnőtt kezdő csoport; a partneroldal szerint kortól és tánctudástól függetlenül várják a csatlakozókat",ageRangeOperational:true,interests:["mozgas","nyelv"],day:"hetkoznap",weekday:"hetfo",weekdays:["hetfo"],pace:"rendszeres",when:"Hétfőnként 19:00–21:00",location:"Bécsi Magyar Iskola, Schwedenplatz 2 / Laurenzerberg 5., 1010 Wien, Top 8",teacher:"Sipos Tibor és Orbán Dalma",sourceNote:"A partneroldal nem ad alsó számszerű korhatárt, és kortól független csatlakozást ír. A programválasztóban a felhasználó által megadott 'felnőtteknek' programbesorolás miatt 18+ operatív sávot használunk.",url:"https://napraforgok.at/r%C3%B3lunk#kezdocsoport",provider:"Napraforgók",sourceType:"partneroldal 2026/27",why:"Belépő szintű magyar néptánc közösségi formában, előzetes tánctudás nélkül is."},
    {id:"mos",name:"Microsoft Office Specialist (MOS) felkészítő tanfolyam",minAge:18,maxAge:99,ageText:"felnőtteknek",ageRangeOperational:true,interests:["tech"],day:"hetkoznap",weekday:"hetfo",weekdays:["hetfo","kedd","szerda","csutortok","pentek"],pace:"rendszeres",when:"Online órák hétfőtől péntekig 9:00–12:00 között; a csoportbeosztás jelentkezés után készül",location:"Online és Bécsben",fee:"690 €-tól; a csomagok tartalmazzák a megjelölt számú MOS vizsgát",sourceNote:"A képzési oldal nem közöl számszerű korhatárt. A 18+ besorolás a programválasztó operatív felnőtt sávja; a pontos óraszám, ütemezés, vizsganyelv és vizsgahelyszín jelentkezés után kerül megerősítésre.",url:"https://mos.magyariskola.at",provider:"BMI",sourceType:"saját képzési oldal 2026/27",why:"Magyar nyelvű, gyakorlati Word-, Excel- és PowerPoint-képzés, célzott felkészítéssel a Microsoft Office Specialist vizsgára."}
  ]
};