(function(){
'use strict';
var ENDPOINT='https://routes.googleapis.com/directions/v2:computeRoutes';
var cfg=window.BMI_FINDER||{};
function pad(n){return String(n).padStart(2,'0')}
function durationSeconds(v){var m=String(v||'').match(/^([\d.]+)s$/);return m?Number(m[1]):NaN}
function programFor(card){var title=card.querySelector('.result-title')||card.querySelector('b'),text=title?title.textContent.trim():card.textContent;return(cfg.programs||[]).find(function(p){return text.indexOf(p.name)!==-1})||null}
function shiftLocal(date,hour,minute,delta){var d=new Date(date+'T00:00:00Z');d.setUTCMinutes(hour*60+minute+delta);return{date:d.getUTCFullYear()+'-'+pad(d.getUTCMonth()+1)+'-'+pad(d.getUTCDate()),hour:d.getUTCHours(),minute:d.getUTCMinutes()}}
function viennaOffset(date){var d=new Date(date+'T12:00:00Z'),parts=new Intl.DateTimeFormat('en',{timeZone:'Europe/Vienna',timeZoneName:'longOffset'}).formatToParts(d),z=parts.find(function(x){return x.type==='timeZoneName'}),m=String(z&&z.value||'GMT+01:00').match(/GMT([+-]\d{2}:\d{2})/);return m?m[1]:'+01:00'}
function rfc3339(local){return local.date+'T'+pad(local.hour)+':'+pad(local.minute)+':00'+viennaOffset(local.date)}
function requestBody(origin,dest,mode,departure){var travelMode=mode==='car'?'DRIVE':mode==='walk'?'WALK':'TRANSIT',body={origin:{location:{latLng:{latitude:origin.lat,longitude:origin.lon}}},destination:{location:{latLng:{latitude:dest.lat,longitude:dest.lon}}},travelMode:travelMode,languageCode:'hu',units:'METRIC'};if(departure&&(travelMode==='DRIVE'||travelMode==='TRANSIT'))body.departureTime=rfc3339(departure);if(travelMode==='DRIVE'){body.routingPreference='TRAFFIC_AWARE_OPTIMAL';body.trafficModel='BEST_GUESS'}return body}
function compute(origin,dest,mode,departure){var key=window.BMI_GOOGLE_ROUTES_API_KEY||'';if(!key)return Promise.reject(new Error('Google Routes API key is not configured.'));return fetch(ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json','X-Goog-Api-Key':key,'X-Goog-FieldMask':'routes.duration,routes.staticDuration,routes.distanceMeters'},body:JSON.stringify(requestBody(origin,dest,mode,departure))}).then(function(r){if(!r.ok)return r.text().then(function(t){throw new Error('Google Routes '+r.status+' '+t.slice(0,160))});return r.json()}).then(function(data){var route=data&&data.routes&&data.routes[0];if(!route)throw new Error('Google Routes returned no route.');var sec=durationSeconds(route.duration),staticSec=durationSeconds(route.staticDuration),meters=Number(route.distanceMeters);if(!Number.isFinite(sec)||!Number.isFinite(meters))throw new Error('Google Routes returned incomplete route data.');return{minutes:sec/60,staticMinutes:Number.isFinite(staticSec)?staticSec/60:null,km:meters/1000}})}
function occurrence(card){var p=programFor(card);return p&&window.BMI_TRANSIT&&typeof window.BMI_TRANSIT.nextOccurrence==='function'?window.BMI_TRANSIT.nextOccurrence(p):null}
function sampleOffsets(mode){return mode==='walk'?[0]:[-60,-30,-10]}
function signature(card,occ){return[card.dataset.routeMode,card.dataset.routeOriginLat,card.dataset.routeOriginLon,card.dataset.routeDestLat,card.dataset.routeDestLon,occ&&occ.date,occ&&occ.hour,occ&&occ.minute,window.BMI_MAP_CONSENT===true?'1':'0',window.BMI_GOOGLE_ROUTES_API_KEY?'key':'nokey'].join('|')}
function apply(card,occ,rows){var mode=card.dataset.routeMode,mins=rows.map(function(x){return x.minutes}),kms=rows.map(function(x){return x.km}),avgMin=mins.reduce(function(a,b){return a+b},0)/mins.length,avgKm=kms.reduce(function(a,b){return a+b},0)/kms.length,min=Math.min.apply(Math,mins),max=Math.max.apply(Math,mins);if(mode==='walk'){min=Math.max(1,avgMin*.92);max=Math.max(min+1,avgMin*1.10)}card.dataset.routeKm=String(avgKm);card.dataset.routeMinutes=String(avgMin);card.dataset.routeMinMinutes=String(min);card.dataset.routeMaxMinutes=String(max);card.dataset.routeEstimated='false';card.dataset.routeProvider='google-routes';card.dataset.routeProviderLabel='Google Routes API';if(occ&&window.BMI_TRANSIT){var w=window.BMI_TRANSIT.windowFor(occ);card.dataset.routeDate=w.date;card.dataset.routeWindow=w.text;card.dataset.routeTargetStart=w.end;if(mode==='transit'){card.dataset.transitKm=String(avgKm);card.dataset.transitMinMinutes=String(min);card.dataset.transitMaxMinutes=String(max);card.dataset.transitDate=w.date;card.dataset.transitWindow=w.text;card.dataset.transitTargetStart=w.end;card.dataset.transitEstimated='false';card.dataset.transitScheduled='true'}}card.dispatchEvent(new CustomEvent('bmi:precise-route-finished',{bubbles:true,detail:{provider:'google-routes',mode:mode,km:avgKm,min:min,max:max,samples:rows.length}}));if(mode==='transit')card.dispatchEvent(new CustomEvent('bmi:transit-finished',{bubbles:true,detail:{provider:'google-routes',estimated:false,km:avgKm,min:min,max:max}}))}
function runCard(card){if(window.BMI_MAP_CONSENT!==true||!window.BMI_GOOGLE_ROUTES_API_KEY)return;var mode=card.dataset.routeMode;if(!/^(car|walk|transit)$/.test(mode))return;var nums=['routeOriginLat','routeOriginLon','routeDestLat','routeDestLon'].map(function(k){return Number(card.dataset[k])});if(!nums.every(Number.isFinite))return;var occ=occurrence(card);if(!occ&&mode!=='walk')return;var sig=signature(card,occ);if(card.dataset.googleRoutesSignature===sig||card.dataset.googleRoutesLoading===sig)return;card.dataset.googleRoutesLoading=sig;var origin={lat:nums[0],lon:nums[1]},dest={lat:nums[2],lon:nums[3]},offsets=sampleOffsets(mode),jobs=offsets.map(function(delta){var dep=occ?shiftLocal(occ.date,occ.hour,occ.minute,delta):null;return compute(origin,dest,mode,dep)});Promise.all(jobs).then(function(rows){card.dataset.googleRoutesSignature=sig;delete card.dataset.googleRoutesLoading;apply(card,occ,rows)}).catch(function(err){delete card.dataset.googleRoutesLoading;card.dataset.googleRoutesError=String(err&&err.message||err);card.dispatchEvent(new CustomEvent('bmi:precise-route-error',{bubbles:true,detail:{provider:'google-routes'}}))})}
function run(){document.querySelectorAll('.result-card').forEach(runCard)}
var mo=new MutationObserver(function(){requestAnimationFrame(run)});mo.observe(document.documentElement,{childList:true,subtree:true});window.addEventListener('bmi-map-consent-change',function(e){if(e.detail&&e.detail.accepted)run()});document.addEventListener('bmi:transit-finished',function(){run()});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run);else run();
window.BMI_PRECISE_ROUTING={provider:'google-routes',configured:function(){return!!window.BMI_GOOGLE_ROUTES_API_KEY},run:run};
})();
