(function(){
'use strict';
var ENDPOINT='https://fahrplan.oebb.at/bin/mgate.exe';
var cfg=window.BMI_FINDER||{};
function pad(n){return String(n).padStart(2,'0')}
function dateKey(d){return d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate())}
function parseStart(p){var m=String(p&&p.when||'').match(/(?:^|\D)([01]?\d|2[0-3])[:.]([0-5]\d)(?!\d)/);return m?{h:+m[1],m:+m[2]}:null}
function closed(iso){var r=cfg.calendarRules||{};if((r.publicHolidays||[]).includes(iso)||(r.schoolFreeDates||[]).includes(iso))return true;return(r.schoolBreaks||[]).some(function(x){return x&&iso>=x[0]&&iso<=x[1]})}
var dayMap=['vasarnap','hetfo','kedd','szerda','csutortok','pentek','szombat'];
function nextOccurrence(p){var st=parseStart(p);if(!st)return null;var today=new Date();today.setHours(0,0,0,0);var dates=(p.eventDates||[]).map(String).map(function(x){return x.slice(0,10)}).filter(function(x){return x>=dateKey(today)&&!(p.blockedEventDates||[]).includes(x)&&!closed(x)}).sort();if(dates.length)return{date:dates[0],hour:st.h,minute:st.m};if(p.scheduleMode==='appointment'||p.exactTodayEligible===false)return null;var days=(Array.isArray(p.weekdays)?p.weekdays:[p.weekday]).filter(Boolean);if(!days.length)return null;for(var i=0;i<35;i++){var d=new Date(today);d.setDate(d.getDate()+i);var iso=dateKey(d);if(days.includes(dayMap[d.getDay()])&&!closed(iso)&&!(p.blockedEventDates||[]).includes(iso))return{date:iso,hour:st.h,minute:st.m}}return null}
function programFor(card){var title=(card.querySelector('.result-title')||card.querySelector('b'));var text=title?title.textContent.trim():card.textContent;return(cfg.programs||[]).find(function(p){return text.indexOf(p.name)!==-1})||null}
function durMinutes(s){var m=String(s||'').match(/^(\d{2})(\d{2})(\d{2})$/);return m?(+m[1]*60)+(+m[2])+(+m[3]/60):null}
function timeMinutes(s){var m=String(s||'').match(/^(\d{2})(\d{2})(\d{2})$/);return m?(+m[1]*60)+(+m[2]):null}
function median(a){a=a.filter(Number.isFinite).sort(function(x,y){return x-y});if(!a.length)return null;var i=Math.floor(a.length/2);return a.length%2?a[i]:(a[i-1]+a[i])/2}
function envelope(req,meth){return{id:'1',ver:'1.67',lang:'deu',formatted:false,auth:{type:'AID',aid:'OWDL4fE4ixNiPBBm'},client:{id:'OEBB',type:'WEB',name:'webapp',l:'vs_webapp'},svcReqL:[{cfg:{polyEnc:'GPA'},req:req,meth:meth,id:'1|1|'}]}}
async function post(body,signal){var r=await fetch(ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:signal});if(!r.ok)throw new Error('http '+r.status);return r.json()}
async function nearestStop(lat,lon,signal){var req={ring:{cCrd:{x:Math.round(lon*1e6),y:Math.round(lat*1e6)},maxDist:-1,minDist:0},locFltrL:[{type:'PROD',mode:'INC',value:'1023'}],getPOIs:false,getStops:true,maxLoc:6};var j=await post(envelope(req,'LocGeoPos'),signal),res=j&&j.svcResL&&j.svcResL[0]&&j.svcResL[0].res,locs=res&&res.locL||[];var stop=locs.find(function(x){return x&&x.lid&&x.type==='S'})||locs.find(function(x){return x&&x.lid});if(!stop||!stop.lid)throw new Error('nearest-stop');return{lid:stop.lid,type:'S',name:stop.name||''}}
async function query(card,p,occ){var olat=+card.dataset.routeOriginLat,olon=+card.dataset.routeOriginLon,dlat=+card.dataset.routeDestLat,dlon=+card.dataset.routeDestLon;if(![olat,olon,dlat,dlon].every(Number.isFinite))throw new Error('coords');var ctl=new AbortController(),tm=setTimeout(function(){ctl.abort()},10000);try{var stops=await Promise.all([nearestStop(olat,olon,ctl.signal),nearestStop(dlat,dlon,ctl.signal)]),date=occ.date.replace(/-/g,''),arrival=pad(occ.hour)+pad(occ.minute)+'00';var req={depLocL:[{lid:stops[0].lid,type:'S'}],arrLocL:[{lid:stops[1].lid,type:'S'}],jnyFltrL:[{type:'PROD',mode:'INC',value:'1023'}],getPolyline:false,getPasslist:false,outDate:date,outTime:arrival,outFrwd:false,numF:6};var j=await post(envelope(req,'TripSearch'),ctl.signal),cons=j&&j.svcResL&&j.svcResL[0]&&j.svcResL[0].res&&j.svcResL[0].res.outConL||[],target=occ.hour*60+occ.minute;var valid=cons.map(function(c){return{duration:durMinutes(c.dur),dep:timeMinutes(c.dep&&c.dep.dTimeS),arr:timeMinutes(c.arr&&c.arr.aTimeS),changes:Number.isFinite(+c.chg)?+c.chg:null}}).filter(function(x){return Number.isFinite(x.duration)&&Number.isFinite(x.arr)&&x.arr<=target&&x.arr>=target-60});if(!valid.length)throw new Error('no-window-results');return{minutes:Math.round(median(valid.map(function(x){return x.duration}))),changes:Math.round(median(valid.map(function(x){return x.changes}).filter(Number.isFinite))),samples:valid.length,date:occ.date,start:pad(occ.hour)+':'+pad(occ.minute),window:pad((occ.hour+23)%24)+':'+pad(occ.minute)+'–'+pad(occ.hour)+':'+pad(occ.minute),originStop:stops[0].name,destinationStop:stops[1].name,source:'ÖBB Scotty / HAFAS'}}finally{clearTimeout(tm)}}
function apply(card,data){card.dataset.transitScheduled='true';card.dataset.transitMinutes=String(data.minutes);card.dataset.transitSamples=String(data.samples);card.dataset.transitChanges=String(data.changes);card.dataset.transitDate=data.date;card.dataset.transitWindow=data.window;card.dataset.transitOriginStop=data.originStop||'';card.dataset.transitDestinationStop=data.destinationStop||'';card.dispatchEvent(new CustomEvent('bmi:transit-ready',{bubbles:true,detail:data}))}
async function runCard(card){if(card.dataset.routeMode!=='transit'||card.dataset.transitLoading==='1'||card.dataset.transitScheduled==='true')return;var p=programFor(card),occ=p&&nextOccurrence(p);if(!occ)return;card.dataset.transitLoading='1';try{apply(card,await query(card,p,occ))}catch(e){card.dataset.transitUnavailable='true';card.dataset.transitReason=String(e&&e.message||'unavailable')}finally{card.dataset.transitLoading='0';card.dispatchEvent(new CustomEvent('bmi:transit-finished',{bubbles:true}))}}
function run(){document.querySelectorAll('.result-card').forEach(runCard)}
var mo=new MutationObserver(run);mo.observe(document.documentElement,{childList:true,subtree:true});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run);else run();
window.BMI_TRANSIT={nextOccurrence:nextOccurrence,endpoint:ENDPOINT};
})();
