(function(){
'use strict';
var cfg=window.BMI_FINDER||{};
function pad(n){return String(n).padStart(2,'0')}
function viennaToday(){var p=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Vienna',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());var pick=function(t){var x=p.find(function(v){return v.type===t});return x&&x.value};return pick('year')+'-'+pick('month')+'-'+pick('day')}
function dateKey(d){return d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate())}
function parseStart(p){var m=String(p&&p.when||'').match(/(?:^|\D)([01]?\d|2[0-3])[:.]([0-5]\d)(?!\d)/);return m?{h:+m[1],m:+m[2]}:null}
function closed(iso){var r=cfg.calendarRules||{};if((r.publicHolidays||[]).includes(iso)||(r.schoolFreeDates||[]).includes(iso))return true;return(r.schoolBreaks||[]).some(function(x){return x&&iso>=x[0]&&iso<=x[1]})}
var dayMap=['vasarnap','hetfo','kedd','szerda','csutortok','pentek','szombat'];
function nextOccurrence(p){var st=parseStart(p);if(!st)return null;var base=viennaToday(),today=new Date(base+'T12:00:00');var dates=(p.eventDates||[]).map(String).map(function(x){return x.slice(0,10)}).filter(function(x){return x>=base&&!(p.blockedEventDates||[]).includes(x)&&!closed(x)}).sort();if(dates.length)return{date:dates[0],hour:st.h,minute:st.m};if(p.scheduleMode==='appointment'||p.exactTodayEligible===false)return null;var days=(Array.isArray(p.weekdays)?p.weekdays:[p.weekday]).filter(Boolean);if(!days.length)return null;for(var i=0;i<35;i++){var d=new Date(today);d.setDate(d.getDate()+i);var iso=dateKey(d);if(days.includes(dayMap[d.getDay()])&&!closed(iso)&&!(p.blockedEventDates||[]).includes(iso))return{date:iso,hour:st.h,minute:st.m}}return null}
function programFor(card){var title=card.querySelector('.result-title')||card.querySelector('b'),text=title?title.textContent.trim():card.textContent;return(cfg.programs||[]).find(function(p){return text.indexOf(p.name)!==-1})||null}
function windowFor(occ){var target=occ.hour*60+occ.minute,start=target-60;return{date:occ.date,start:pad(Math.floor((start+1440)%1440/60))+':'+pad((start+1440)%60),end:pad(occ.hour)+':'+pad(occ.minute),text:pad(Math.floor((start+1440)%1440/60))+':'+pad((start+1440)%60)+'–'+pad(occ.hour)+':'+pad(occ.minute)}}
function applyTarget(card,occ){var w=windowFor(occ);card.dataset.transitScheduled='false';card.dataset.transitUnavailable='true';card.dataset.transitReason='trusted-backend-unavailable';card.dataset.transitDate=w.date;card.dataset.transitWindow=w.text;card.dataset.transitTargetStart=w.end;delete card.dataset.transitMinutes;delete card.dataset.transitKm;delete card.dataset.transitSamples;delete card.dataset.transitChanges;card.dispatchEvent(new CustomEvent('bmi:transit-finished',{bubbles:true,detail:{date:w.date,window:w.text,start:w.end,available:false}}))}
function runCard(card){if(card.dataset.routeMode!=='transit'||card.dataset.transitTargetResolved==='true')return;var p=programFor(card),occ=p&&nextOccurrence(p);card.dataset.transitTargetResolved='true';if(occ)applyTarget(card,occ);else{card.dataset.transitUnavailable='true';card.dataset.transitReason='no-confirmed-next-occurrence';card.dispatchEvent(new CustomEvent('bmi:transit-finished',{bubbles:true,detail:{available:false}}))}}
function run(){document.querySelectorAll('.result-card').forEach(runCard)}
var mo=new MutationObserver(run);mo.observe(document.documentElement,{childList:true,subtree:true});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run);else run();
window.BMI_TRANSIT={nextOccurrence:nextOccurrence,windowFor:windowFor,providerStatus:'backend-required'};
})();
