(function(){
'use strict';
var BASE='https://v6.db.transport.rest';
var cfg=window.BMI_FINDER||{};
function pad(n){return String(n).padStart(2,'0')}
function dateKey(d){return d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate())}
function parseStart(p){var m=String(p&&p.when||'').match(/(?:^|\D)([01]?\d|2[0-3])[:.]([0-5]\d)(?!\d)/);return m?{h:+m[1],m:+m[2]}:null}
function closed(iso){var r=cfg.calendarRules||{};if((r.publicHolidays||[]).includes(iso)||(r.schoolFreeDates||[]).includes(iso))return true;return(r.schoolBreaks||[]).some(function(x){return x&&iso>=x[0]&&iso<=x[1]})}
var dayMap=['vasarnap','hetfo','kedd','szerda','csutortok','pentek','szombat'];
function nextOccurrence(p){var st=parseStart(p);if(!st)return null;var today=new Date();today.setHours(0,0,0,0);var dates=(p.eventDates||[]).map(String).map(function(x){return x.slice(0,10)}).filter(function(x){return x>=dateKey(today)&&!(p.blockedEventDates||[]).includes(x)&&!closed(x)}).sort();if(dates.length)return{date:dates[0],hour:st.h,minute:st.m};if(p.scheduleMode==='appointment'||p.exactTodayEligible===false)return null;var days=(Array.isArray(p.weekdays)?p.weekdays:[p.weekday]).filter(Boolean);if(!days.length)return null;for(var i=0;i<35;i++){var d=new Date(today);d.setDate(d.getDate()+i);var iso=dateKey(d);if(days.includes(dayMap[d.getDay()])&&!closed(iso)&&!(p.blockedEventDates||[]).includes(iso))return{date:iso,hour:st.h,minute:st.m}}return null}
function programFor(card){var title=(card.querySelector('.result-title')||card.querySelector('b'));var text=title?title.textContent.trim():card.textContent;return(cfg.programs||[]).find(function(p){return text.indexOf(p.name)!==-1})||null}
function median(a){a=a.filter(Number.isFinite).sort(function(x,y){return x-y});if(!a.length)return null;var i=Math.floor(a.length/2);return a.length%2?a[i]:(a[i-1]+a[i])/2}
function hav(a,b){var R=6371,p1=a[1]*Math.PI/180,p2=b[1]*Math.PI/180,dp=(b[1]-a[1])*Math.PI/180,dl=(b[0]-a[0])*Math.PI/180,q=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.asin(Math.sqrt(q))}
function geometryKm(poly){var total=0,seen=false;function line(coords){if(!Array.isArray(coords))return;for(var i=1;i<coords.length;i++)if(Array.isArray(coords[i-1])&&Array.isArray(coords[i])){total+=hav(coords[i-1],coords[i]);seen=true}}var feats=poly&&poly.features||[];feats.forEach(function(f){var g=f&&f.geometry;if(!g)return;if(g.type==='LineString')line(g.coordinates);else if(g.type==='MultiLineString')(g.coordinates||[]).forEach(line)});return seen?total:null}
function journeyKm(j){var total=0,seen=false;(j.legs||[]).forEach(function(l){var x=geometryKm(l.polyline);if(Number.isFinite(x)){total+=x;seen=true}else if(Number.isFinite(l.distance)){total+=l.distance/1000;seen=true}});return seen?total:null}
function viennaOffset(iso){var d=new Date(iso+'T12:00:00Z'),z=new Intl.DateTimeFormat('en',{timeZone:'Europe/Vienna',timeZoneName:'longOffset'}).formatToParts(d).find(function(x){return x.type==='timeZoneName'}),m=String(z&&z.value||'GMT+01:00').match(/GMT([+-])(\d{2}):?(\d{2})/);return m?m[1]+m[2]+':'+m[3]:'+01:00'}
function isoAt(date,mins){mins=(mins+1440)%1440;return date+'T'+pad(Math.floor(mins/60))+':'+pad(mins%60)+':00'+viennaOffset(date)}
async function getJson(url,signal){var r=await fetch(url,{headers:{Accept:'application/json'},signal:signal});if(!r.ok)throw new Error('http '+r.status);return r.json()}
function nearbyList(j){return Array.isArray(j)?j:(Array.isArray(j.locations)?j.locations:Array.isArray(j.stops)?j.stops:[])}
async function nearestStop(lat,lon,signal){var u=BASE+'/locations/nearby?latitude='+encodeURIComponent(lat)+'&longitude='+encodeURIComponent(lon)+'&distance=900&results=8&profile=dbnav';var a=nearbyList(await getJson(u,signal)),s=a.find(function(x){return x&&(x.type==='stop'||x.type==='station')&&x.id})||a.find(function(x){return x&&x.id});if(!s)throw new Error('nearest-stop');return s}
function journeyTimes(j){var legs=j&&j.legs||[],first=legs[0]||{},last=legs[legs.length-1]||{},dep=new Date(first.departure||first.plannedDeparture||j.departure),arr=new Date(last.arrival||last.plannedArrival||j.arrival);return{dep:dep,arr:arr,duration:(arr-dep)/60000,changes:Math.max(0,legs.filter(function(l){return l&&l.line}).length-1)}}
async function query(card,p,occ){var olat=+card.dataset.routeOriginLat,olon=+card.dataset.routeOriginLon,dlat=+card.dataset.routeDestLat,dlon=+card.dataset.routeDestLon;if(![olat,olon,dlat,dlon].every(Number.isFinite))throw new Error('coords');var ctl=new AbortController(),tm=setTimeout(function(){ctl.abort()},10000);try{var stops=await Promise.all([nearestStop(olat,olon,ctl.signal),nearestStop(dlat,dlon,ctl.signal)]),target=occ.hour*60+occ.minute,windowStart=target-60,depIso=isoAt(occ.date,windowStart),u=BASE+'/journeys?from='+encodeURIComponent(stops[0].id)+'&to='+encodeURIComponent(stops[1].id)+'&departure='+encodeURIComponent(depIso)+'&results=12&polylines=true&stopovers=false&remarks=false&tickets=false&profile=dbnav';var j=await getJson(u,ctl.signal),journeys=j&&j.journeys||[],targetDate=new Date(isoAt(occ.date,target)),startDate=new Date(depIso),valid=journeys.map(function(x){var t=journeyTimes(x);return{duration:t.duration,changes:t.changes,dep:t.dep,arr:t.arr,km:journeyKm(x)}}).filter(function(x){return Number.isFinite(x.duration)&&x.dep>=startDate&&x.arr<=targetDate});if(!valid.length)throw new Error('no-window-results');var km=median(valid.map(function(x){return x.km}));return{minutes:Math.round(median(valid.map(function(x){return x.duration}))),km:Number.isFinite(km)?Math.round(km*10)/10:null,changes:Math.round(median(valid.map(function(x){return x.changes}))),samples:valid.length,date:occ.date,start:pad(occ.hour)+':'+pad(occ.minute),window:pad(Math.floor((windowStart+1440)%1440/60))+':'+pad((windowStart+1440)%60)+'–'+pad(occ.hour)+':'+pad(occ.minute),originStop:stops[0].name||'',destinationStop:stops[1].name||'',source:'DB Navigator REST'}}finally{clearTimeout(tm)}}
function apply(card,data){card.dataset.transitScheduled='true';card.dataset.transitMinutes=String(data.minutes);if(Number.isFinite(data.km))card.dataset.transitKm=String(data.km);card.dataset.transitSamples=String(data.samples);card.dataset.transitChanges=String(data.changes);card.dataset.transitDate=data.date;card.dataset.transitWindow=data.window;card.dataset.transitOriginStop=data.originStop||'';card.dataset.transitDestinationStop=data.destinationStop||'';card.dispatchEvent(new CustomEvent('bmi:transit-ready',{bubbles:true,detail:data}))}
async function runCard(card){if(card.dataset.routeMode!=='transit'||card.dataset.transitLoading==='1'||card.dataset.transitScheduled==='true')return;var p=programFor(card),occ=p&&nextOccurrence(p);if(!occ)return;card.dataset.transitLoading='1';try{apply(card,await query(card,p,occ))}catch(e){card.dataset.transitUnavailable='true';card.dataset.transitReason=String(e&&e.message||'unavailable')}finally{card.dataset.transitLoading='0';card.dispatchEvent(new CustomEvent('bmi:transit-finished',{bubbles:true}))}}
function run(){document.querySelectorAll('.result-card').forEach(runCard)}
var mo=new MutationObserver(run);mo.observe(document.documentElement,{childList:true,subtree:true});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run);else run();window.BMI_TRANSIT={nextOccurrence:nextOccurrence,base:BASE};
})();